"use client";
import { useRef, useState } from 'react';
import { editPrivateDraft, privateDraft, type AutomationStatus, type PrivateDraft } from '@/lib/client-api';
import { Icon } from './icon';

function issue(value: unknown): string { return typeof value === 'string' ? value : value && typeof value === 'object' ? String((value as Record<string, unknown>).message ?? (value as Record<string, unknown>).description ?? (value as Record<string, unknown>).code ?? '待核对事项') : String(value); }
export function AutomationDrafts({ data, reload }: { data: AutomationStatus | null; reload: () => Promise<void> }) {
  const [selected, setSelected] = useState<PrivateDraft | null>(null), [title, setTitle] = useState(''), [text, setText] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  async function open(id: string) { try { const draft = await privateDraft(id); setSelected(draft); setTitle(draft.title); setText(draft.bodyBlocks.map(block=>block.text).join('\n\n')); dialog.current?.showModal(); } catch (error) { setNotice(error instanceof Error ? error.message : '草稿读取失败'); } }
  async function save() {
    if (!selected) return; setBusy(true);
    try { const blocks = text.split(/\n\s*\n/).map(block => block.trim()).filter(Boolean); const draft = await editPrivateDraft(selected, { title, body_blocks: blocks.map((text,index)=>({type:selected.bodyBlocks[index]?.type??'paragraph',text})), claim_refs: selected.claimRefs.filter(ref => ref.blockIndex < blocks.length).map(ref => ({ block_index: ref.blockIndex, claim_id: ref.claimId })) }); setSelected(draft); setNotice('人工修改已保存为新版本，原始生成稿和依据继续保留。'); await reload(); }
    catch (error) { setNotice(error instanceof Error ? error.message : '草稿未保存'); } finally { setBusy(false); }
  }
  const drafts = data?.drafts ?? [];
  return <>
    <div className="ui-notice"><Icon name="lock" size={16}/><span>AI 候选稿仅团队可见。待核实事实、公开许可和发布规则分别检查。</span></div>
    {notice && <p className="ui-notice" role="status">{notice}</p>}
    <div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>自动草稿</th><th>版本 / 模式</th><th>证据</th><th>公开阻塞</th><th>操作</th></tr></thead><tbody>{drafts.map(draft => <tr key={draft.id}><td><button type="button" className="ui-task-name" onClick={() => open(draft.id)}>{draft.title}</button><span className="ui-task-meta">主题 {draft.topicId.slice(0, 8)}</span></td><td>第 {draft.version} 版<span className="ui-task-meta">{draft.origin==='manual'?'人工修改':draft.mode === 'mock' ? '模拟生成' : '真实模型生成'}</span></td><td>{draft.sourceVersionIds.length} 个来源版本 · {draft.claimRefs.length} 处引用</td><td><span className="ui-status" data-tone="amber">{draft.gaps.length + draft.warnings.length || '待复核'}</span></td><td><button type="button" className="ui-button ui-button-quiet" onClick={() => open(draft.id)}>查看与编辑<Icon name="chevron" size={14}/></button></td></tr>)}</tbody></table>{!drafts.length && <div className="ui-table-empty"><strong>尚无自动生成草稿</strong><p>真实来源变化经洞察和主题推荐后，后台在规则范围内生成私有候选稿。</p></div>}</div>
    <dialog ref={dialog} className="ui-drawer" aria-labelledby="auto-draft-title">{selected && <><header className="ui-drawer-header"><div><span className="ui-task-meta">第 {selected.version} 版 · {selected.origin==='manual'?'人工修改':selected.mode === 'mock' ? '模拟生成' : '真实模型生成'} · 私有候选</span><h2 id="auto-draft-title">{selected.title}</h2></div><button type="button" className="ui-icon-button" aria-label="关闭自动草稿" onClick={() => dialog.current?.close()}><Icon name="close" size={20}/></button></header><div className="ui-drawer-body"><label className="ui-field">标题<input value={title} required maxLength={300} onChange={event => setTitle(event.target.value)}/></label><label className="ui-field">正文<textarea rows={14} required maxLength={30000} value={text} onChange={event => setText(event.target.value)}/></label><section className="ui-detail-section"><h3>来源与生成依据</h3><p>主题：{selected.topicId}</p><p>生成运行：{selected.aiRunId ?? '无模型运行引用'}</p><ul>{selected.sourceVersionIds.map(id => <li key={id}>{String(data?.source_changes.find(source => source.id === id)?.title ?? '来源版本')} · {id}</li>)}</ul>{selected.claimRefs.length > 0 && <p>{selected.claimRefs.map(ref => `第 ${ref.blockIndex + 1} 段：${ref.claimId}`).join('；')}</p>}<p className="ui-field-hint ui-draft-fingerprint">当前版本哈希：{selected.payloadHash}</p></section><section className="ui-detail-section"><h3>发布前待核对</h3>{[...selected.gaps, ...selected.warnings].length ? <ul>{[...selected.gaps, ...selected.warnings].map((value, index) => <li key={index}>{issue(value)}</li>)}</ul> : <p>候选稿仍需独立事实、公开许可、素材和发布审核。</p>}</section>{notice && <p role="status">{notice}</p>}</div><footer className="ui-drawer-footer"><span className="ui-field-hint">保留生成稿、人工修改与来源历史</span><button type="button" className="ui-button ui-button-primary" disabled={busy || !title.trim() || !text.trim()} onClick={save}>{busy ? '保存中…' : '保存私有新版本'}</button></footer></>}</dialog>
  </>;
}
