"use client";
import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import {api} from '@/lib/client-api';
import {Icon} from './icon';
type Row=Record<string,unknown>;
const lines:Record<string,string>={yonyou:'用友',seeyon:'致远',shared:'集成服务'};
export function ContentWorkspace(){
 const [items,setItems]=useState<Row[]>([]),[pages,setPages]=useState<Row[]>([]),[claims,setClaims]=useState<Row[]>([]),[policies,setPolicies]=useState<Row[]>([]),[tab,setTab]=useState('content'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Row|null>(null),[versions,setVersions]=useState<Row[]>([]),[title,setTitle]=useState(''),[text,setText]=useState(''),[line,setLine]=useState('shared'),[claimIds,setClaimIds]=useState<string[]>([]),[policyId,setPolicyId]=useState(''),[selectedPage,setSelectedPage]=useState<Row|null>(null),[preview,setPreview]=useState<Row|null>(null);
 const drawer=useRef<HTMLDialogElement>(null),pageDrawer=useRef<HTMLDialogElement>(null);
 async function load(){try{const result=await Promise.all([api<Row[]>('/content'),api<Row[]>('/pages'),api<Row[]>('/claims'),api<Row[]>('/execution-policies')]);setItems(result[0]);setPages(result[1]);setClaims(result[2].filter(claim=>claim.verification_status==='verified'&&claim.public_permission==='allowed'&&claim.assertion_type==='fact'));setPolicies(result[3].filter(policy=>policy.status==='active'));}catch(error){setNotice(error instanceof Error?error.message:'内容读取失败');}}
 useEffect(()=>{void load();},[]);
 async function open(item?:Row){try{setDraft(item??null);setTitle(String(item?.title??''));setLine(String(item?.business_line??'shared'));setText('');setClaimIds([]);const rows=item?await api<Row[]>(`/content/${item.id}/versions`):[];setVersions(rows);const latest=rows[0];if(latest){const modules=(latest.body_json as Row).modules as Row[];const solution=modules.find(module=>module.type==='solution');const data=solution?.data as Row|undefined;setText(((data?.body??[]) as Row[]).map(block=>block.text).join('\n\n'));setTitle(String(latest.title??item?.title));setClaimIds((latest.claim_ids??[]) as string[]);}drawer.current?.showModal();}catch(error){setNotice(error instanceof Error?error.message:'草稿读取失败');}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const item=draft??await api<Row>('/content',{method:'POST',body:{title,kind:'article',business_line:line}});setDraft(item);const body=text.split(/\n\s*\n/).filter(Boolean).map(paragraph=>({type:'paragraph',text:paragraph}));const modules=[{type:'hero',schema_version:1,data:{headline:title,description:'企业数字化服务内容',cta:{label:'了解服务范围',href:'/service/',action:'navigate'}}},{type:'solution',schema_version:1,data:{heading:'内容说明',body,claim_ids:claimIds}}];const version=await api<Row>(`/content/${item.id}/versions`,{method:'POST',version:Number(versions[0]?.version_no??0),body:{title,modules,claim_ids:claimIds}});setVersions(await api<Row[]>(`/content/${item.id}/versions`));setNotice('不可变内容版本已保存，发布前请审核事实与许可。');await load();}catch(error){setNotice(error instanceof Error?error.message:'保存失败');}finally{setBusy(false);}}
 async function review(){const latest=versions[0];if(!latest)return;setBusy(true);try{await api(`/content/versions/${latest.id}/review`,{method:'POST',version:Number(latest.version_no),body:{review_status:'approved',reason:'人工核对正文与事实许可'}});setNotice('该内容版本已审核。');setVersions(await api<Row[]>(`/content/${draft!.id}/versions`));await load();}catch(error){setNotice(error instanceof Error?error.message:'审核未完成');}finally{setBusy(false);}}
 async function createPage(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const form=new FormData(event.currentTarget);const session=await api<{actor_id:string}>('/session');const path=String(form.get('path')).trim().replace(/\/+$/, '');const item=items.find(value=>value.id===form.get('content_item_id'))!;const origin=String(form.get('origin'));const url=new URL(path,origin);const page=await api<Row>('/pages',{method:'POST',body:{host:url.host,path,business_line:item.business_line,template_key:'article',content_item_id:item.id,seo_title:String(form.get('title')),description:String(form.get('description')),canonical_url:url.href,index_policy:'noindex',owner_user_id:session.actor_id}});setNotice('官网页面已登记。发布范围由服务器配置再次校验。');pageDrawer.current?.close();setSelectedPage(await api<Row>(`/pages/${page.page_id}`));await load();}catch(error){setNotice(error instanceof Error?error.message:'页面未创建');}finally{setBusy(false);}}
 async function inspectPage(page:Row){try{setSelectedPage(page);setPreview(await api<Row>(`/pages/${page.id}/preview`));}catch(error){setNotice(error instanceof Error?error.message:'预览失败');}}
 async function publish(){if(!selectedPage||!policyId)return;setBusy(true);try{const rows=await api<Row[]>(`/content/${selectedPage.content_item_id}/versions`);const latest=rows[0];if(!latest||latest.review_status!=='approved')throw new Error('先审核最新内容版本，再发布页面。');const action=await api<Row>('/actions',{method:'POST',body:{action_type:'content.publish',target:{page_id:selectedPage.id},version_id:latest.id,policy_version_id:policyId,expected_payload_hash:latest.payload_hash}});const result=await api<Row>(`/pages/${selectedPage.id}/publish`,{method:'POST',version:Number(selectedPage.version),body:{action_id:action.id,content_version_id:latest.id}});setNotice(`页面版本已切换；平台核验状态：${String(result.state??'待读回')}。`);setSelectedPage(null);setPreview(null);await load();}catch(error){setNotice(error instanceof Error?error.message:'发布未完成');}finally{setBusy(false);}}
 return <><div className="ui-page-header"><div><h1>内容与官网</h1><p>保存正文版本，审核事实与许可，管理官网发布。</p></div><button className="ui-button ui-button-primary" type="button" onClick={()=>tab==='content'?open():pageDrawer.current?.showModal()}>{tab==='content'?'新建内容':'新建页面'}</button></div><div className="ui-tabs" role="group" aria-label="内容分类">{[['content','内容草稿'],['pages','官网页面']].map(([key,name])=><button key={key} type="button" aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key!)}>{name}</button>)}</div>{notice&&<p className="ui-notice" role="status">{notice}</p>}
 <div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>名称</th><th>业务线</th><th>版本 / 状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{(tab==='content'?items:pages).map(item=><tr key={String(item.id)}><td>{String(item.title??item.seo_title)}<span className="ui-row-subtitle">{String(item.path??item.kind??'')}</span></td><td>{lines[String(item.business_line)]}</td><td>{tab==='content'?`第 ${String(item.version??0)} 版 · ${item.review_status==='approved'?'已审核':'待审核'}`:item.published_release_id?'已有发布版本':'未发布'}</td><td>{new Date(String(item.updated_at)).toLocaleString('zh-CN')}</td><td><button className="ui-button ui-button-quiet" type="button" onClick={()=>tab==='content'?open(item):inspectPage(item)}>详情<Icon name="chevron" size={14}/></button></td></tr>)}</tbody></table>{!(tab==='content'?items:pages).length&&<div className="ui-table-empty"><strong>暂无{tab==='content'?'内容草稿':'官网页面'}</strong><p>从右上角添加第一条记录。</p></div>}</div>
 {selectedPage&&<section className="ui-panel ui-detail-section"><h2>{String(selectedPage.seo_title)}</h2><p>{String(selectedPage.path)}</p>{preview&&<p>预览已读取：当前内容与页面均从数据库获取。</p>}<label className="ui-field">发布授权规则<select value={policyId} onChange={event=>setPolicyId(event.target.value)}><option value="">选择已启用规则</option>{policies.map(policy=><option key={String(policy.id)} value={String(policy.active_version_id)}>{String(policy.name)}</option>)}</select></label><button className="ui-button ui-button-primary" type="button" disabled={busy||!policyId} onClick={publish}>发布当前审核版本</button><button className="ui-button" type="button" onClick={()=>{setSelectedPage(null);setPreview(null);}}>关闭详情</button></section>}
 <dialog className="ui-drawer" ref={drawer} aria-labelledby="content-title"><form onSubmit={save}><header className="ui-drawer-header"><h2 id="content-title">{draft?'编辑内容':'新建内容'}</h2><button className="ui-icon-button" type="button" aria-label="关闭内容" onClick={()=>drawer.current?.close()}><Icon name="close" size={20}/></button></header><div className="ui-drawer-body"><label className="ui-field">标题<input required maxLength={100} value={title} onChange={event=>setTitle(event.target.value)}/></label><label className="ui-field">业务线<select value={line} disabled={Boolean(draft)} onChange={event=>setLine(event.target.value)}>{Object.entries(lines).map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label><label className="ui-field">正文<textarea required rows={12} maxLength={20000} value={text} onChange={event=>setText(event.target.value)} placeholder="段落之间空一行。事实表述须选择已核实的公开证据。"/></label><fieldset className="ui-field ui-channel-options"><legend>已核实的公开事实</legend>{claims.map(claim=><label key={String(claim.id)}><input type="checkbox" checked={claimIds.includes(String(claim.id))} onChange={event=>setClaimIds(event.target.checked?[...claimIds,String(claim.id)]:claimIds.filter(id=>id!==claim.id))}/>{String(claim.claim_text)}</label>)}{!claims.length&&<p className="ui-muted">暂无可公开引用的已核实事实。</p>}</fieldset><p className="ui-field-hint">共 {versions.length} 个不可变正文版本。平台发布还需校准账号档案和实际素材。</p>{notice&&<p role="status">{notice}</p>}</div><footer className="ui-drawer-footer"><button type="button" className="ui-button" disabled={busy||!versions.length||versions[0]?.review_status==='approved'} onClick={review}>审核当前版本</button><button className="ui-button ui-button-primary" disabled={busy}>{busy?'保存中…':'保存新版本'}</button></footer></form></dialog>
 <dialog className="ui-drawer" ref={pageDrawer} aria-labelledby="page-title"><form onSubmit={createPage}><header className="ui-drawer-header"><h2 id="page-title">新建官网页面</h2><button className="ui-icon-button" type="button" aria-label="关闭页面表单" onClick={()=>pageDrawer.current?.close()}><Icon name="close" size={20}/></button></header><div className="ui-drawer-body"><label className="ui-field">内容<select name="content_item_id" required>{items.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.title)}</option>)}</select></label><label className="ui-field">官网地址<input name="origin" type="url" required defaultValue="http://localhost:3001"/></label><label className="ui-field">模块路径<input name="path" required placeholder="/article/service-preparation"/></label><label className="ui-field">SEO 标题<input name="title" required maxLength={100}/></label><label className="ui-field">页面描述<textarea name="description" required maxLength={500}/></label></div><footer className="ui-drawer-footer"><button className="ui-button ui-button-primary" disabled={busy||!items.length}>保存页面</button></footer></form></dialog></>;
}
