"use client";
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/client-api';
import {Icon} from './icon';
type Row=Record<string,unknown>;
type Member={id:string;name:string;roles:string[]};
const stages:Record<string,string>={CONTACTED:'已联系',QUALIFIED:'销售确认',OPPORTUNITY:'商机',DEMO:'演示',PROPOSAL:'方案',QUOTED:'报价',WON:'成交',LOST:'丢单',NURTURE:'培育',REACTIVATED:'重新激活'};
export function LeadsWorkspace(){
 const [leads,setLeads]=useState<Row[]>([]),[captures,setCaptures]=useState<Row[]>([]),[conversations,setConversations]=useState<Row[]>([]),[members,setMembers]=useState<Member[]>([]),[tab,setTab]=useState('leads'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Row|null>(null),[owner,setOwner]=useState(''),[need,setNeed]=useState(''),[note,setNote]=useState(''),[next,setNext]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const drawer=useRef<HTMLDialogElement>(null);
 async function load(){try{const leadRows=await api<Row[]>('/leads');setLeads(leadRows);const values=await Promise.allSettled([api<Row[]>('/contact-captures'),api<Row[]>('/reception/conversations'),api<Member[]>('/workspace/members')]);if(values[0].status==='fulfilled')setCaptures(values[0].value);if(values[1].status==='fulfilled')setConversations(values[1].value);if(values[2].status==='fulfilled')setMembers(values[2].value);}catch(error){setNotice(error instanceof Error?error.message:'共享记录读取失败');}}
 useEffect(()=>{void load();},[]);
 function open(lead:Row){setSelected(lead);setOwner(String(lead.owner_user_id??''));setNeed(String(lead.need??''));const feedback=(lead.feedback_json??{}) as Row;setNote(String(feedback.note??''));setNext(String(feedback.next_step??''));drawer.current?.showModal();}
 async function save(){if(!selected)return;setBusy(true);try{await api(`/leads/${selected.id}`,{method:'PATCH',version:Number(selected.version),body:{...(owner?{owner_user_id:owner}:{}),...(need.trim()?{need}:{}),note,feedback:{next_step:next}}});setNotice('线索归属及反馈已保存。');drawer.current?.close();await load();}catch(error){setNotice(error instanceof Error?error.message:'更新失败');}finally{setBusy(false);}}
 async function requestPrivacy(request_type:string){if(!selected)return;setBusy(true);try{const contact=await api<Row>(`/contacts/${selected.contact_id}`);await api(`/contacts/${selected.contact_id}/privacy-requests`,{method:'POST',version:Number(contact.version),body:{request_type,reason:'运营记录联系人提出的处理请求'}});setNotice('请求已持久保存；后续处理会核查下游回执。');drawer.current?.close();await load();}catch(error){setNotice(error instanceof Error?error.message:'请求未完成');}finally{setBusy(false);}}
 const rows=tab==='leads'?leads:tab==='captures'?captures:conversations;
 return <><div className="ui-page-header"><div><h1>共享线索</h1><p>两名运营共享处理；联系人、留资和有效线索分别核验。</p></div><button type="button" className="ui-button" onClick={load}>刷新记录</button></div><section className="ui-kpi-strip"><div className="ui-kpi"><span>留资记录</span><strong>{captures.length}</strong><small>尚待可联系及意图核实</small></div><div className="ui-kpi"><span>真实线索</span><strong>{leads.filter(lead=>!lead.test_record).length}</strong><small>已核实的企业意图</small></div><div className="ui-kpi"><span>销售确认</span><strong>{leads.filter(lead=>!lead.test_record&&lead.quality_level==='qualified_lead').length}</strong><small>负责人及下一步已明确</small></div><div className="ui-kpi"><span>接待会话</span><strong>{conversations.length}</strong><small>含明确标记的测试会话</small></div></section>{notice&&<p className="ui-notice" role="status">{notice}</p>}<section className="ui-toolbar"><div className="ui-tabs" role="group" aria-label="线索分类">{[['leads','有效线索'],['captures','留资记录'],['reception','接待会话']].map(([key,name])=><button key={key} type="button" aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key!)}>{name}</button>)}</div><label className="ui-search-field"><Icon name="search" size={16}/><input type="search" aria-label="搜索企业与需求" value={search} onChange={event=>setSearch(event.target.value)} placeholder="搜索企业、需求或状态"/></label></section>
 <div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>企业 / 会话</th><th>需求 / 来源</th><th>处理状态</th><th>质量 / 阶段</th><th>负责人</th><th>操作</th></tr></thead><tbody>{rows.filter(row=>`${row.company??''} ${row.need??''} ${row.state??''}`.includes(search)).map(row=><tr key={String(row.id)}><td>{String(row.company??(tab==='reception'?'接待会话':'待确认企业'))}<span className="ui-row-subtitle">{String(row.id).slice(0,8)}{row.test_record?' · 测试记录':''}</span></td><td>{String(row.need??row.source_channel??'实时接待')}</td><td>{String(row.status??row.state??(row.counted_real_lead?'已核实':'待核实'))}</td><td>{tab==='leads'?`${row.quality_level==='qualified_lead'?'销售确认':'真实线索'} · ${stages[String(row.funnel_stage)]??'未进入销售阶段'}`:tab==='captures'?'留资记录':'接待消息'}</td><td>{members.find(member=>member.id===row.owner_user_id)?.name??'未分配'}</td><td>{tab==='leads'?<button className="ui-button ui-button-quiet" type="button" onClick={()=>open(row)}>处理<Icon name="chevron" size={14}/></button>:<span className="ui-muted">{tab==='captures'?'需实际证据确认':'回执持续核验'}</span>}</td></tr>)}</tbody></table>{!rows.length&&<div className="ui-table-empty"><strong>暂无{tab==='leads'?'有效线索':tab==='captures'?'留资记录':'接待会话'}</strong><p>官网表单和接待平台接通后，记录会进入这里。</p></div>}</div>
 <dialog className="ui-drawer" ref={drawer} aria-labelledby="lead-title">{selected&&<><header className="ui-drawer-header"><div><span className="ui-muted">第 {String(selected.version)} 版{selected.test_record?' · 测试记录':''}</span><h2 id="lead-title">{String(selected.company??'咨询线索')}</h2></div><button className="ui-icon-button" type="button" aria-label="关闭线索详情" onClick={()=>drawer.current?.close()}><Icon name="close" size={20}/></button></header><div className="ui-drawer-body"><label className="ui-field">负责人<select value={owner} onChange={event=>setOwner(event.target.value)}><option value="">未分配</option>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="ui-field">需求<textarea aria-label="线索需求" rows={4} maxLength={3000} value={need} onChange={event=>setNeed(event.target.value)}/></label><label className="ui-field">下一步<textarea aria-label="线索下一步" rows={3} maxLength={1000} value={next} onChange={event=>setNext(event.target.value)}/></label><label className="ui-field">处理备注<textarea aria-label="线索备注" rows={3} maxLength={1000} value={note} onChange={event=>setNote(event.target.value)}/></label><section className="ui-detail-section"><h3>联系人处理请求</h3><p className="ui-field-hint">仅在联系人实际提出请求后记录。撤回会取消后续自动营销任务。</p><button className="ui-button" type="button" disabled={busy} onClick={()=>requestPrivacy('withdraw')}>记录撤回请求</button><button className="ui-button" type="button" disabled={busy} onClick={()=>requestPrivacy('delete')}>记录删除请求</button></section>{notice&&<p role="status">{notice}</p>}</div><footer className="ui-drawer-footer"><button className="ui-button" type="button" onClick={()=>drawer.current?.close()}>关闭</button><button className="ui-button ui-button-primary" type="button" disabled={busy} onClick={save}>{busy?'保存中…':'保存反馈'}</button></footer></>}</dialog></>;
}
