"use client";
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Icon} from './icon';
import {api} from '@/lib/client-api';
type Task={id:string;title:string;type:string;business_line:string;status:string;owner_name:string;due_at:string;version:number;brief:Record<string,unknown>};
type Overview={tasks:Task[];connections:{id:string;display_name:string;access_status:string;health:string}[];runs:{id:string;kind:string;status:string;created_at:string}[];exceptions:{id:string;action_type:string;state:string;last_error:unknown}[];mode:string;externalWritesEnabled:boolean};
const labels:Record<string,string>={todo:'待处理',doing:'进行中',blocked:'受阻',done:'已完成',cancelled:'已取消',queued:'排队中',running:'运行中',succeeded:'已完成',needs_human:'需人工处理',unknown:'结果待核对',failed:'失败',partial:'部分完成'};
const business:Record<string,string>={yonyou:'用友',seeyon:'致远',shared:'集成服务'};
function day(value:string){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));}
function time(value:string){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));}
function tone(status:string){return status==='done'||status==='succeeded'?'green':status==='blocked'||status==='needs_human'||status==='unknown'||status==='failed'?'amber':status==='doing'||status==='running'?'blue':'neutral';}
export function OverviewWorkspace(){
  const [data,setData]=useState<Overview>({tasks:[],connections:[],runs:[],exceptions:[],mode:'',externalWritesEnabled:false});
  const [tab,setTab]=useState('全部'),[search,setSearch]=useState(''),[owner,setOwner]=useState('全部负责人'),[date,setDate]=useState(day(new Date().toISOString()));
  const [selected,setSelected]=useState<Task|null>(null),[note,setNote]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
  const drawer=useRef<HTMLDialogElement>(null);
  async function load(){try{setData(await api<Overview>('/workspace/overview'));}catch(error){setNotice(error instanceof Error?error.message:'任务读取失败');}}
  useEffect(()=>{let active=true;api<Overview>('/workspace/overview').then(value=>{if(active)setData(value);}).catch(error=>{if(active)setNotice(error.message);});return()=>{active=false;};},[]);
  const scoped=useMemo(()=>data.tasks.filter(task=>day(task.due_at)===date&&(owner==='全部负责人'||task.owner_name===owner)),[data.tasks,date,owner]);
  function matches(task:Task,value:string){return value==='全部'||value==='待处理'&&['todo','blocked'].includes(task.status)||value==='进行中'&&task.status==='doing'||value==='已完成'&&task.status==='done';}
  const tasks=scoped.filter(task=>matches(task,tab)&&`${task.title} ${task.type} ${business[task.business_line]??task.business_line}`.includes(search.trim()));
  function open(task:Task){setSelected(task);setNote(String(task.brief.operator_note??''));drawer.current?.showModal();}
  async function save(){if(!selected)return;setSaving(true);try{const saved=await api<Task>(`/tasks/${selected.id}`,{method:'PATCH',version:selected.version,body:{brief:{...selected.brief,operator_note:note}}});setSelected({...saved,owner_name:selected.owner_name});setNotice('处理备注已保存，团队成员可以查看。');await load();drawer.current?.close();}catch(error){setNotice(error instanceof Error?error.message:'保存失败');}finally{setSaving(false);}}
  return <>
    <div className="ui-page-header"><div><h1>今日工作</h1><p>推进任务，处理例外，查看共享运行结果。</p></div><div className="ui-page-actions"><span className="ui-status" data-tone="neutral">{data.mode==='mock'?'本地测试':'组织工作区'}</span><button type="button" className="ui-button ui-button-primary" onClick={()=>{setTab('待处理');setSearch('');}}>处理待办</button></div></div>
    <div className="ui-notice"><Icon name="eye" size={16}/><span>{data.mode==='mock'?'本地测试记录已保存到数据库，真实平台能力待接入验收。':'执行任务按照当前授权规则运行。'}</span><Link href="/settings">连接设置<Icon name="chevron" size={14}/></Link></div>
    <section className="ui-toolbar"><div className="ui-toolbar-filters"><label className="ui-filter-field"><span>工作日期</span><input type="date" aria-label="工作日期" value={date} onChange={event=>setDate(event.target.value)}/></label><label className="ui-filter-field"><span>负责人</span><select aria-label="负责人" value={owner} onChange={event=>setOwner(event.target.value)}><option>全部负责人</option>{[...new Set(data.tasks.map(task=>task.owner_name))].map(name=><option key={name}>{name}</option>)}</select></label></div><button className="ui-button" type="button" onClick={load}>刷新记录</button></section>
    <section className="ui-kpi-strip" aria-label="任务统计">{[['待处理',scoped.filter(task=>task.status==='todo').length,'推进记录待处理'],['受阻',scoped.filter(task=>task.status==='blocked').length,'查看阻塞原因'],['进行中',scoped.filter(task=>task.status==='doing').length,'任务正在推进'],['已完成',scoped.filter(task=>task.status==='done').length,'已保存的推进记录']].map(([name,count,hint])=><div className="ui-kpi" key={name}><span>{name}</span><strong>{count}</strong><small>{hint}</small></div>)}</section>
    {notice&&<div className="ui-toast" role="status"><span>{notice}</span><button className="ui-icon-button" type="button" aria-label="关闭提示" onClick={()=>setNotice('')}><Icon name="close" size={16}/></button></div>}
    <div className="ui-work-grid"><section className="ui-panel ui-task-panel"><header className="ui-panel-header"><h2>工作任务 <span className="ui-count">{scoped.length}</span></h2><label className="ui-search"><Icon name="search" size={16}/><input type="search" aria-label="搜索任务" placeholder="搜索任务、主题或类型" value={search} onChange={event=>setSearch(event.target.value)}/></label></header><div className="ui-tabs" role="group" aria-label="任务状态">{['全部','待处理','进行中','已完成'].map(value=><button key={value} type="button" aria-pressed={tab===value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{value}<span>{scoped.filter(task=>matches(task,value)).length}</span></button>)}</div>
    <div className="ui-table-wrap"><table className="ui-table"><thead><tr><th>任务</th><th>业务线 / 类型</th><th>状态</th><th>负责人</th><th>计划时间</th><th>操作</th></tr></thead><tbody>{tasks.map(task=><tr key={task.id}><td><button className="ui-task-name" type="button" onClick={()=>open(task)}>{task.title}</button><span className="ui-task-meta">{task.id.slice(0,8)}</span></td><td>{business[task.business_line]??task.business_line}<span className="ui-task-meta">{task.brief.workspace==='theme'?'主题推进':task.type}</span></td><td><span className="ui-status" data-tone={tone(task.status)}>{labels[task.status]??task.status}</span></td><td>{task.owner_name}</td><td>{time(task.due_at)}</td><td><button className="ui-button ui-button-quiet" type="button" onClick={()=>open(task)}>详情<Icon name="chevron" size={14}/></button></td></tr>)}</tbody></table>{!tasks.length&&<div className="ui-empty"><strong>当前筛选没有任务</strong><p>可以调整日期和负责人，或在推广主题中添加推进任务。</p><Link className="ui-button" href="/themes">管理主题</Link></div>}</div><footer className="ui-table-footer"><span>显示 {tasks.length} / {scoped.length} 项任务</span><span>团队共享 · 数据库记录</span></footer></section>
    <aside className="ui-work-aside"><section className="ui-panel"><header className="ui-panel-header"><h2>执行例外</h2><span className="ui-status" data-tone="amber">{data.exceptions.length}</span></header><div className="ui-panel-body">{data.exceptions.length?data.exceptions.map(item=><div className="ui-connection-row" key={item.id}><span>{item.action_type}</span><span className="ui-status" data-tone="amber">{labels[item.state]??item.state}</span></div>):<p className="ui-muted">暂无执行例外</p>}</div></section>
    <section className="ui-panel"><header className="ui-panel-header"><h2>账号连接</h2><Link className="ui-text-link" href="/settings">管理</Link></header><div className="ui-panel-body ui-connection-list">{data.connections.length?data.connections.map(item=><div className="ui-connection-row" key={item.id}><span>{item.display_name}</span><span className="ui-status" data-tone={item.health==='healthy'?'green':'neutral'}>{item.access_status==='connected'?'已连接':'待验证'}</span></div>):<p className="ui-muted">尚未配置账号连接</p>}</div></section>
    <section className="ui-panel"><header className="ui-panel-header"><h2>运行记录</h2><span className="ui-muted">持久记录</span></header><div className="ui-panel-body"><ol className="ui-log-list">{data.runs.map(run=><li className="ui-log-item" key={run.id}><span className="ui-status-dot" data-tone={tone(run.status)}/><div><span>{run.kind} · {labels[run.status]??run.status}</span><small>{day(run.created_at)} {time(run.created_at)}</small></div></li>)}</ol>{!data.runs.length&&<p className="ui-muted">暂无运行记录</p>}</div></section></aside></div>
    <dialog className="ui-drawer" ref={drawer} aria-labelledby="task-detail-title">{selected&&<><header className="ui-drawer-header"><div><span className="ui-task-meta">{selected.id.slice(0,8)} · 第 {selected.version} 版</span><h2 id="task-detail-title">{selected.title}</h2></div><button className="ui-icon-button" type="button" aria-label="关闭任务详情" onClick={()=>drawer.current?.close()}><Icon name="close" size={20}/></button></header><div className="ui-drawer-body"><div className="ui-detail-grid"><div><span>状态</span><strong>{labels[selected.status]??selected.status}</strong></div><div><span>负责人</span><strong>{selected.owner_name}</strong></div><div><span>业务线</span><strong>{business[selected.business_line]??selected.business_line}</strong></div><div><span>计划时间</span><strong>{day(selected.due_at)} {time(selected.due_at)}</strong></div></div><section className="ui-detail-section"><h3>任务范围</h3><p>{selected.brief.workspace==='theme'?'主题推进任务。完成状态由推广主题中的任务清单维护。':'任务执行结果以对应运行记录和平台回读证据为准。'}</p></section><label className="ui-field">处理备注<textarea aria-label="处理备注" maxLength={1000} rows={5} value={note} onChange={event=>setNote(event.target.value)}/></label></div><footer className="ui-drawer-footer"><button className="ui-button" type="button" onClick={()=>drawer.current?.close()}>关闭</button><button className="ui-button ui-button-primary" type="button" disabled={saving} onClick={save}>{saving?'保存中…':'保存处理备注'}</button></footer></>}</dialog>
  </>;
}
