"use client";
import {useEffect,useState} from 'react';
import type {FormEvent} from 'react';
import {api} from '@/lib/client-api';
import {Icon} from './icon';
type Row=Record<string,unknown>;
const sources=[['公开市场信息','批准的网站与查询范围','market_public','public_web'],['竞品公开推广','指定竞品网站与活动','competitor_public','public_web'],['Mac / Google Drive','指定资料目录的增量变化','mac_drive','google_drive'],['ChatGPT 指定会话','授权会话与实际确认消息','chatgpt','chatgpt_authorized']];
export function SettingsContent(){
 const [tab,setTab]=useState('sources'),[connections,setConnections]=useState<Row[]>([]),[accounts,setAccounts]=useState<Row[]>([]),[policies,setPolicies]=useState<Row[]>([]),[channels,setChannels]=useState<Row[]>([]),[notice,setNotice]=useState(''),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null),[settings,setSettings]=useState<Row[]>([]);
 async function load(){try{const values=await Promise.all([api<Row[]>('/connections'),api<Row[]>('/platform-accounts'),api<Row[]>('/execution-policies'),api<Row[]>('/distribution-manifest'),api<Row[]>('/settings')]);setConnections(values[0]);setAccounts(values[1]);setPolicies(values[2]);setChannels(values[3]);setSettings(values[4]);}catch(error){setNotice(error instanceof Error?error.message:'配置读取失败');}}
 useEffect(()=>{void load();},[]);
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{
   const provider=String(form.get('provider')),external=String(form.get('external')),name=String(form.get('name'));
   const source=sources.find(item=>item[2]===provider);
   const connection=await api<Row>('/connections',{method:'POST',body:{provider:source?source[3]:provider,account_external_id:external,display_name:name,...(source?{source_kind:source[2]}:{})}});
   if(!source&&provider!=='baidu_ads')await api('/platform-accounts',{method:'POST',body:{connection_id:connection.id,channel_id:provider,account_external_id:external,display_name:name}});
   setAdding(false);setNotice('连接信息已保存；实际读取、会话和发布能力仍须验证。');await load();
 }catch(error){setNotice(error instanceof Error?error.message:'保存失败');}finally{setBusy(false);}}
 async function inspect(policy:Row){try{setSelected(await api<Row>(`/execution-policies/${policy.id}`));}catch(error){setNotice(error instanceof Error?error.message:'规则读取失败');}}
 async function newPolicy(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const form=new FormData(event.currentTarget);const accountIds = form.getAll('account_ids').map(String); const action = String(form.get('action')); const limit = Number(form.get('daily_limit')); const budget = (field:string) => form.get(field) ? Math.round(Number(form.get(field)) * 100) : null; const value = {business_scope:{business_lines:form.getAll('business_lines').map(String)}, account_ids:accountIds, allowed_actions:[action], currency:'CNY', daily_budget_minor:budget('daily_budget'),total_budget_minor:budget('total_budget'),max_bid_change_pct:action==='ads.update'?10:null,publish_frequency:{daily_max:limit,weekly_max:limit*7,min_interval_minutes:60},publish_windows:[{timezone:'Asia/Shanghai',account_ids:accountIds,weekdays:[1,2,3,4,5],start:'09:00',end:'18:00'}],stop_conditions:{max_errors:3},valid_from:new Date().toISOString(),valid_until:new Date(String(form.get('valid_until'))+'T15:59:59Z').toISOString(),allowed_ad_operations:action.startsWith('ads.')?[action==='ads.pause'?'pause':'update']:[],allowed_ad_entity_levels:action.startsWith('ads.')?['campaign','unit','keyword','creative']:[],approved_path_prefixes:String(form.get('paths')??'').split(',').map(path=>path.trim().replace(/\/+$/, '')).filter(Boolean),reception_scope:{}};await api('/execution-policies',{method:'POST',body:{name:String(form.get('name')),definition:value}});setNotice('规则草稿已保存，负责人批准后才能启用。');setAdding(false);await load();}catch(error){setNotice(error instanceof Error?error.message:'规则保存失败');}finally{setBusy(false);}}
 async function approveAndActivate(){if(!selected)return;setBusy(true);try{const versions=selected.versions as Row[];const version=versions?.[0];if(!version)throw new Error('规则缺少版本');await api(`/execution-policies/${selected.id}/activate`,{method:'POST',version:Number(selected.version),body:{version_id:version.id}});setNotice('规则已批准并启用。运行环境的外部写入开关仍独立控制。');setSelected(null);await load();}catch(error){setNotice(error instanceof Error?error.message:'规则未启用');}finally{setBusy(false);}}
 async function saveSchedule(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const form=new FormData(event.currentTarget);const config=settings.find(item=>item.key==='operating_schedule');await api('/settings/operating_schedule',{method:'PUT',version:Number(config?.schema_version??0),body:{enabled:form.get('enabled')==='on',timezone:'Asia/Shanghai',workflows:form.getAll('workflows'),business_lines:['yonyou','seeyon','shared'],goal_ids:[],...(form.get('policy_version_id')?{policy_version_id:form.get('policy_version_id')}:{})}});setNotice('周期配置已保存，后台会创建当前周期中尚未安排的任务。');await load();}catch(error){setNotice(error instanceof Error?error.message:'周期配置未保存');}finally{setBusy(false);}}
 return <div className="settings-content"><div className="ui-tabs" role="group" aria-label="设置分类">{[['sources','资料来源'],['accounts','平台账号'],['rules','执行规则'],['schedule','周期任务']].map(([key,name])=><button key={key} type="button" aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>{setTab(key!);setAdding(false);setSelected(null);}}>{name}</button>)}</div>
 {notice&&<p className="ui-notice" role="status">{notice}</p>}
 <div className="ui-section-heading"><h3>{tab==='sources'?'四类信息来源':tab==='accounts'?'平台账号':tab==='schedule'?'周期任务':'持续执行规则'}</h3>{tab!=='schedule'&&<button className="ui-button" type="button" onClick={()=>{setAdding(!adding);setSelected(null);}}>{adding?'收起':tab==='rules'?'新建规则':'添加连接'}</button>}</div>
 {adding&&['sources','accounts'].includes(tab)&&<form onSubmit={add}><label className="ui-field">名称<input name="name" required maxLength={100}/></label><label className="ui-field">类型<select name="provider">{tab==='sources'?sources.map(item=><option key={item[2]} value={item[2]}>{item[0]}</option>):<><option value="baidu_ads">百度营销报表与广告</option>{channels.map(item=><option key={String(item.channelId)} value={String(item.channelId)}>{String(item.displayName??item.channelId)}</option>)}</>}</select></label><label className="ui-field">账号或目录标识<input name="external" required maxLength={200} placeholder="测试标识或批准的真实账号 ID"/></label><button className="ui-button ui-button-primary" disabled={busy}>{busy?'保存中…':'保存连接'}</button></form>}
 {adding&&tab==='rules'&&<form onSubmit={newPolicy}><label className="ui-field">规则名称<input name="name" required maxLength={100}/></label><fieldset className="ui-field ui-channel-options"><legend>业务线</legend>{[['yonyou','用友'],['seeyon','致远'],['shared','集成服务']].map(([value,name])=><label key={value}><input name="business_lines" type="checkbox" value={value} defaultChecked/>{name}</label>)}</fieldset><fieldset className="ui-field ui-channel-options"><legend>授权账号</legend>{accounts.map(item=><label key={String(item.id)}><input name="account_ids" type="checkbox" value={String(item.id)}/>{String(item.display_name)}</label>)}</fieldset><label className="ui-field">允许动作<select name="action"><option value="external.publish">渠道内容发布</option><option value="content.publish">官网模块发布</option><option value="content.unpublish">官网模块撤回</option><option value="ads.update">百度广告更新</option><option value="ads.pause">百度广告暂停</option></select></label><div className="ui-form-grid"><label className="ui-field">每日发布上限<input name="daily_limit" type="number" min="1" max="20" defaultValue="2" required/></label><label className="ui-field">有效至<input name="valid_until" type="date" required/></label><label className="ui-field">广告日预算（元）<input name="daily_budget" type="number" min="0" step="0.01"/></label><label className="ui-field">广告总预算（元）<input name="total_budget" type="number" min="0" step="0.01"/></label></div><label className="ui-field">批准的官网路径前缀<input name="paths" placeholder="/service, /industry"/></label><p className="ui-field-hint">发布时间为工作日 09:00–18:00；连续 3 次执行错误后停止。保存后需负责人核对并启用。</p><button className="ui-button ui-button-primary" disabled={busy}>{busy?'保存中…':'保存规则草稿'}</button></form>}
 {tab==='sources'&&<><div className="ui-settings-list">{sources.map(([name,detail,kind])=>{const connection=connections.find(item=>item.source_kind===kind);return <div className="ui-setting-row" key={kind}><Icon name="link" size={18}/><div><strong>{name}</strong><p>{connection?String(connection.display_name):detail}</p></div><span className="ui-status" data-tone={connection?.access_status==='connected'?'green':'amber'}>{connection?.access_status==='connected'?'已连接':connection?'待验证':'未配置'}</span></div>;})}</div><p className="ui-field-hint">连接标识与授权读取范围分别核验；未配置读取器时明确返回采集缺口。</p></>}
 {tab==='accounts'&&<><div className="ui-settings-list">{accounts.map(item=><div className="ui-setting-row" key={String(item.id)}><Icon name="layers" size={18}/><div><strong>{String(item.display_name)}</strong><p>{String(item.channel_id)}</p></div><span className="ui-status" data-tone="neutral">{item.session_status==='active' && Boolean(item.last_session_verified_at)?'会话已验证':'会话待验证'}</span></div>)}{!accounts.length&&<p className="ui-muted">尚未保存平台账号。</p>}</div><p className="ui-field-hint">16 个渠道分别记录实际能力与发布读回证据。</p></>}
 {tab==='schedule'&&<form onSubmit={saveSchedule} key={String(settings.find(item=>item.key==='operating_schedule')?.schema_version??0)}><label className="ui-field"><span><input type="checkbox" name="enabled" defaultChecked={Boolean((settings.find(item=>item.key==='operating_schedule')?.value as Row|undefined)?.enabled)}/> 启用周期任务</span></label><fieldset className="ui-field ui-channel-options"><legend>任务类型</legend>{[['source_watch','四源监测'],['insight_topics','洞察与主题'],['weekly_plan','每周计划'],['metrics_collect','指标整理'],['daily_report','每日报告'],['seo_review','SEO 复核'],['geo_review','GEO 复核'],['archive','报告归档']].map(([value,name])=><label key={value}><input type="checkbox" name="workflows" value={value} defaultChecked={((settings.find(item=>item.key==='operating_schedule')?.value as Row|undefined)?.workflows as string[]|undefined)?.includes(value!)}/>{name}</label>)}</fieldset><label className="ui-field">洞察授权规则<select name="policy_version_id"><option value="">未选择</option>{policies.filter(policy=>policy.status==='active').map(policy=><option key={String(policy.id)} value={String(policy.active_version_id)}>{String(policy.name)}</option>)}</select></label><p className="ui-field-hint">上海时区；Mac资料每15分钟、ChatGPT会话每30分钟；市场/竞品每日；07:20检查前一业务日数据、07:50固化质量、08:00日报与周一计划、12:00日报修订，SEO/GEO周五。读取器或模型缺失时保留人工待办。</p><button className="ui-button ui-button-primary" disabled={busy}>{busy?'保存中…':'保存周期配置'}</button></form>}
 {tab==='rules'&&<><div className="ui-settings-list">{policies.map(item=><button className="ui-setting-row" type="button" key={String(item.id)} onClick={()=>inspect(item)}><Icon name="lock" size={18}/><div><strong>{String(item.name)}</strong><p>第 {String(item.version)} 版</p></div><span className="ui-status" data-tone={item.status==='active'?'green':'neutral'}>{item.status==='active'?'已启用':item.status==='revoked'?'已撤销':'草稿'}</span></button>)}{!policies.length&&<p className="ui-muted">尚未建立持续执行规则。</p>}</div>{selected&&<section className="ui-detail-section"><h3>{String(selected.name)}</h3><p>启用前请核对当前版本的账号、预算和有效期。</p><pre style={{whiteSpace:'pre-wrap',fontSize:12}}>{JSON.stringify(selected.versions,null,2)}</pre><button type="button" className="ui-button ui-button-primary" disabled={busy||selected.status==='active'} onClick={approveAndActivate}>批准并启用当前版本</button></section>}<dl className="ui-definition-list"><div><dt>付费地域</dt><dd>上海、江苏、浙江、安徽</dd></div><div><dt>外部写入</dt><dd>本地测试默认关闭</dd></div><div><dt>真实留资</dt><dd>须完整配置隐私告知和处理许可</dd></div></dl></>}
 </div>;
}
