import test from 'node:test';
import assert from 'node:assert/strict';
import {createTestDatabase,DEMO_OWNER_ID,DEMO_MARKETER_ID} from '@boran/db';
import {stableHash,uuid} from '@boran/domain/core';
import {cleanupPublicEvents} from '../src/public-events-cleanup';
test('worker retention entry deletes expired records in the configured org, retains receipt audit and checks live service authorization',async()=>{
 const db=await createTestDatabase();const org=uuid(),foreign=uuid();const time=new Date('2026-10-03T01:00:00Z');
 try{
  for(const id of [org,foreign]){await db.query("INSERT INTO organizations(id,name,timezone,base_currency) VALUES($1,'脱敏清理验收组织','Asia/Shanghai','CNY')",[id]);await db.query("INSERT INTO memberships(org_id,user_id,roles,active) VALUES($1,$2,'{owner,marketer}',true)",[id,DEMO_OWNER_ID]);}
  async function record(orgId:string,retention:string|null){const page=uuid(),event=uuid();await db.query("INSERT INTO pages(id,org_id,host,path,owner_system,business_line,canonical_url,index_policy,owner_user_id) VALUES($1,$2,'example.invalid',$3,'marketing','shared',$4,'noindex',$5)",[page,orgId,`/test/${page}`,`https://example.invalid/test/${page}`,DEMO_OWNER_ID]);const row=(await db.query("INSERT INTO web_events(org_id,event_id,event_type,occurred_at,received_at,page_id,attribution,properties) VALUES($1,$2,'page_view',$3,$3,$4,'{}',$5) RETURNING id",[orgId,event,time.toISOString(),page,JSON.stringify({synthetic:true,...(retention?{retention_until:retention}:{})})])).rows[0]!;return {id:row.id,event};}
  const expired=await record(org,'2026-10-02T01:00:00.000Z'),fresh=await record(org,'2026-10-04T01:00:00.000Z'),other=await record(foreign,'2026-10-02T01:00:00.000Z'),legacy=await record(org,null);await db.query("INSERT INTO idempotency_records(org_id,scope,key,request_hash,status_code,response_json,resource_id,expires_at) VALUES($1,'public_web_event',$2,$3,202,'{}',$4,$5)",[org,expired.event,stableHash({event:expired.event}),expired.id,'2026-11-03T01:00:00Z']);
  await assert.rejects(cleanupPublicEvents(db,{BORAN_MODE:'live',APP_ENV:'production'}),{code:'EVENTS_CLEANUP_NOT_CONFIGURED'});await assert.rejects(cleanupPublicEvents(db,{BORAN_MODE:'mock',APP_ENV:'production',AUTH_MODE:'mock'}),{code:'EVENTS_CLEANUP_NOT_CONFIGURED'});
  const environment={BORAN_MODE:'live',APP_ENV:'production',BORAN_ORG_ID:org,PUBLIC_EVENTS_CLEANUP_ACTOR_ID:DEMO_OWNER_ID};const result=await cleanupPublicEvents(db,environment,()=>time);assert.equal(result.deleted_count,1);assert.equal(result.mode,'live');assert.equal((await db.query('SELECT id FROM web_events WHERE id=$1',[expired.id])).rowCount,0);for(const row of [fresh,other,legacy])assert.equal((await db.query('SELECT id FROM web_events WHERE id=$1',[row.id])).rowCount,1);assert.equal((await db.query("SELECT key FROM idempotency_records WHERE org_id=$1 AND scope='public_web_event' AND key=$2",[org,expired.event])).rowCount,1);
  const audit=(await db.query("SELECT actor_type,actor_id,details FROM audit_logs WHERE org_id=$1 AND action='analytics.retention_pruned'",[org])).rows[0]!;assert.equal(audit.actor_type,'service');assert.equal(audit.actor_id,DEMO_OWNER_ID);assert.equal((audit.details as Record<string,unknown>).deleted_count,1);
  await db.query('UPDATE users SET active=false WHERE id=$1',[DEMO_OWNER_ID]);await assert.rejects(cleanupPublicEvents(db,environment,()=>time),{code:'FORBIDDEN'});await db.query('UPDATE users SET active=true WHERE id=$1',[DEMO_OWNER_ID]);await assert.rejects(cleanupPublicEvents(db,{...environment,PUBLIC_EVENTS_CLEANUP_ACTOR_ID:DEMO_MARKETER_ID},()=>time),{code:'FORBIDDEN'});assert.equal((await cleanupPublicEvents(db,environment,()=>time)).deleted_count,0);
 }finally{await db.close();}
});
