import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,rm,writeFile,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRuntimeSourceReaders,SourceObjectStore,extractSourceText,extractSourceTextAsync,type SourceReadRequest,type SourceReadResult} from '../src/sources';
import {isPublicSourceAddress} from '../src/source-runtime';

const driveRequest:SourceReadRequest={orgId:'test-org',connectionId:'test-drive',sourceKind:'mac_drive',credentialRef:'env:TEST_DRIVE_OAUTH',scope:{folderIds:['authorized-root']},cursor:null};
const pptxMime='application/vnd.openxmlformats-officedocument.presentationml.presentation';
function crc32(bytes:Buffer):number{let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^(0xedb88320&-(crc&1));}return (crc^0xffffffff)>>>0;}
function zip(entries:Record<string,string>):Buffer {
 const locals:Buffer[]=[],directory:Buffer[]=[];let offset=0;
 for(const [name,content] of Object.entries(entries)){const filename=Buffer.from(name),bytes=Buffer.from(content),local=Buffer.alloc(30),central=Buffer.alloc(46),crc=crc32(bytes);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(bytes.length,18);local.writeUInt32LE(bytes.length,22);local.writeUInt16LE(filename.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(bytes.length,20);central.writeUInt32LE(bytes.length,24);central.writeUInt16LE(filename.length,28);central.writeUInt32LE(offset,42);locals.push(local,filename,bytes);directory.push(central,filename);offset+=local.length+filename.length+bytes.length;}
 const index=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(entries).length,8);end.writeUInt16LE(Object.keys(entries).length,10);end.writeUInt32LE(index.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,index,end]);
}
function pptx(text:string):Buffer{return zip({'ppt/slides/slide1.xml':`<p:sld><a:p><a:r><a:t>${text}</a:t></a:r></a:p></p:sld>`,'ppt/slides/slide2.xml':'<p:sld><a:p><a:r><a:t>真实推广方案 &amp; 服务</a:t></a:r></a:p></p:sld>','ppt/notesSlides/notesSlide1.xml':'<p:notes><a:p><a:r><a:t>交付范围备注</a:t></a:r></a:p></p:notes>'});}
function pdf(pages:string[]):Buffer {
 const fontId=3+pages.length*2,objects:string[]=['<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Kids [${pages.map((_,index)=>`${3+index*2} 0 R`).join(' ')}] /Count ${pages.length} >>`];
 for(const [index,text] of pages.entries()){const contents=text?`BT /F1 12 Tf 40 700 Td (${text.replace(/[\\()]/g,value=>'\\'+value)}) Tj ET`:'';objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${4+index*2} 0 R >>`,`<< /Length ${Buffer.byteLength(contents)} >>\nstream\n${contents}\nendstream`);}objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');let body='%PDF-1.4\n';const offsets=[0];for(const [index,object] of objects.entries()){offsets.push(Buffer.byteLength(body));body+=`${index+1} 0 obj\n${object}\nendobj\n`;}const xref=Buffer.byteLength(body);body+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>String(offset).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(body);
}
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}});
function fakeDrive(state:{version:string;text:string;deleted?:boolean;unsupported?:boolean;expireCursor?:boolean;failList?:boolean;failDownload?:boolean;authFailure?:boolean}) {
 const calls:string[]=[],bytes=()=>state.unsupported?Buffer.from('opaque'):pptx(state.text);
 const file=()=>({id:'nested-material',name:'测试经营方案.pptx',mimeType:state.unsupported?'application/pdf':pptxMime,parents:['nested-folder'],version:state.version,modifiedTime:`2026-10-04T00:00:0${state.version}Z`,md5Checksum:createHash('md5').update(bytes()).digest('hex')});
 const fetcher=(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>{const url=new URL(String(input));calls.push(`${url.pathname}?${url.searchParams.toString()}`);if(state.authFailure)return json({error:'redacted'},401);assert.equal((init?.headers as Record<string,string>)?.authorization,'Bearer test-oauth-token');
  if(url.pathname.endsWith('/changes/startPageToken'))return json({startPageToken:'start-'+state.version});
  if(url.pathname.endsWith('/changes')){if(state.expireCursor){state.expireCursor=false;return json({},410);}return json({changes:[],newStartPageToken:'next-'+state.version});}
  if(url.pathname.endsWith('/files/authorized-root'))return json({id:'authorized-root',name:'授权资料',mimeType:'application/vnd.google-apps.folder'});
  if(url.pathname.endsWith('/files/nested-material'))return url.searchParams.get('alt')==='media'?(state.failDownload?json({},500):new Response(bytes(),{headers:{'content-type':file().mimeType}})):json(file());
  if(url.pathname.endsWith('/files')){if(state.failList)return json({},500);const parent=url.searchParams.get('q');if(parent?.includes("'authorized-root'"))return json({files:[{id:'nested-folder',name:'子目录',mimeType:'application/vnd.google-apps.folder',parents:['authorized-root']}]});if(parent?.includes("'nested-folder'"))return json({files:state.deleted?[]:[file()]});}
  throw new Error('Unexpected provider request');
 }) as typeof fetch;return {fetcher,calls};
}
async function root() {return mkdtemp(join(tmpdir(),'boran-sources-'));}
function changed(result:SourceReadResult):asserts result is Extract<SourceReadResult,{status:'changed'|'partial'}>{assert.equal(result.status,'changed');}

test('PPTX extracts actual slide and notes text with stable slide locators; hostile ZIP is rejected',()=>{
 const extracted=extractSourceText(pptx('用友方案'),pptxMime);assert.equal(extracted.format,'pptx');assert.match(extracted.text,/\[Slide 1\]\n用友方案/);assert.match(extracted.text,/真实推广方案 & 服务/);assert.match(extracted.text,/交付范围备注/);
 assert.throws(()=>extractSourceText(zip({'../ppt/slides/slide1.xml':'<a:t>bad</a:t>'}),pptxMime),/SOURCE_ARCHIVE_INVALID/);
 assert.throws(()=>extractSourceText(Buffer.from('PDF bytes'),'application/pdf'),/SOURCE_CONTENT_UNSUPPORTED/);
});
test('PPTX image-only content cannot become fabricated source text; mixed slides, charts and layout objects stay partial',()=>{
 const image='<p:pic><p:blipFill><a:blip r:embed="rId1"/></p:blipFill></p:pic>',chart='<p:graphicFrame><a:graphic><a:graphicData><c:chart r:id="rId2"/></a:graphicData></a:graphic></p:graphicFrame>';
 assert.throws(()=>extractSourceText(zip({'ppt/slides/slide1.xml':`<p:sld>${image}</p:sld>`}),pptxMime),/SOURCE_PPTX_OCR_REQUIRED/);
 const mixed=extractSourceText(zip({'ppt/slides/slide1.xml':'<p:sld><a:p><a:r><a:t>实际可验证服务范围</a:t></a:r></a:p></p:sld>','ppt/slides/slide2.xml':`<p:sld>${image}</p:sld>`}),pptxMime);
 assert.match(mixed.text,/实际可验证服务范围/);assert.ok(mixed.gaps?.some(gap=>gap.includes('第2页')&&gap.includes('OCR')));
 const chartText=extractSourceText(zip({'ppt/slides/slide1.xml':`<p:sld><a:p><a:r><a:t>实际图表标题</a:t></a:r></a:p>${chart}</p:sld>`}),pptxMime);assert.ok(chartText.gaps?.some(gap=>gap.includes('图表')));
 const layout=extractSourceText(zip({'ppt/slides/slide1.xml':'<p:sld><a:p><a:r><a:t>实际幻灯片正文</a:t></a:r></a:p></p:sld>','ppt/slideMasters/slideMaster1.xml':`<p:sldMaster>${image}</p:sldMaster>`}),pptxMime);assert.ok(layout.gaps?.some(gap=>gap.includes('母版')));
 const notes=extractSourceText(zip({'ppt/slides/slide1.xml':`<p:sld>${image}</p:sld>`,'ppt/notesSlides/notesSlide1.xml':'<p:notes><a:p><a:r><a:t>实际备注内容</a:t></a:r></a:p></p:notes>'}),pptxMime);assert.match(notes.text,/实际备注内容/);assert.ok(notes.gaps?.length);
});
test('Drive mixed PPTX coverage holds the complete cursor; image-only PPTX produces no fake snapshot',async()=>{
 const directory=await root(),state={version:'1',text:'实际服务范围'},fake=fakeDrive(state);let imageOnly=false;
 try{
  const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>'test-oauth-token',fetch:(async(input,init)=>{
   const url=new URL(String(input)),response=await fake.fetcher(input,init);
   const bytes=zip({'ppt/slides/slide1.xml':`<p:sld>${imageOnly?'':'<a:p><a:r><a:t>实际服务范围</a:t></a:r></a:p>'}<p:pic><p:blipFill><a:blip r:embed="rId1"/></p:blipFill></p:pic></p:sld>`});
   if(url.pathname.endsWith('/files/nested-material')){if(url.searchParams.get('alt')==='media')return new Response(bytes);const metadata=await response.json() as Record<string,unknown>;return json({...metadata,md5Checksum:createHash('md5').update(bytes).digest('hex')});}
   if(url.pathname.endsWith('/files')&&url.searchParams.get('q')?.includes("'nested-folder'")){const output=await response.json() as {files:Record<string,unknown>[]};return json({...output,files:output.files.map((file:Record<string,unknown>)=>({...file,md5Checksum:createHash('md5').update(bytes).digest('hex')}))});}
   return response;
  }) as typeof fetch}).mac_drive,request={...driveRequest,cursor:{previous:'complete-watermark'}};
  const partial=await reader.read(request);assert.equal(partial.status,'partial');if(partial.status==='partial'){assert.deepEqual(partial.nextCursor,request.cursor);assert.equal(partial.snapshots.length,1);assert.equal(partial.snapshots[0]!.coverage.status,'partial');assert.match(partial.gaps.join(' '),/OCR/);const snapshot=partial.snapshots[0]!;assert.match(await new SourceObjectStore(directory).readText({orgId:request.orgId,connectionId:request.connectionId,objectKey:snapshot.textObjectKey!,expectedHash:snapshot.textHash!}),/实际服务范围/);}
  imageOnly=true;const empty=await reader.read(request);assert.equal(empty.status,'partial');if(empty.status==='partial'){assert.deepEqual(empty.nextCursor,request.cursor);assert.equal(empty.snapshots.length,0);assert.ok(empty.gaps.length);}
 }finally{await rm(directory,{recursive:true,force:true});}
});
test('PDF actual text layer extraction runs with page limits; scanned or missing text stays an explicit OCR gap',async()=>{
 const extracted=await extractSourceTextAsync(pdf(['Boran marketing plan','Confirmed service scope']),'application/pdf');assert.equal(extracted.format,'pdf');assert.match(extracted.text,/\[Page 1\]\nBoran marketing plan/);assert.match(extracted.text,/Confirmed service scope/);assert.equal(extracted.gaps,undefined);
 const mixed=await extractSourceTextAsync(pdf(['Real source evidence','']),'application/pdf');assert.match(mixed.text,/Real source evidence/);assert.deepEqual(mixed.gaps,['PDF第2页没有可验证文字层，需OCR']);await assert.rejects(extractSourceTextAsync(pdf(['']),'application/pdf'),/SOURCE_PDF_OCR_REQUIRED/);await assert.rejects(extractSourceTextAsync(pdf(['a','b']),'application/pdf',{maxPages:1}),/SOURCE_CONTENT_LIMIT/);await assert.rejects(extractSourceTextAsync(pdf(['a']),'application/pdf',{timeoutMs:1}),/SOURCE_PDF_READ_TIMEOUT/);
});
test('PDF partial coverage preserves original public-source watermark while storing actual available evidence',async()=>{
 const directory=await root();try{const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>null,fetch:(async()=>new Response(pdf(['Actual source business evidence','']),{headers:{'content-type':'application/pdf'}})) as typeof fetch,resolveHost:async()=>[{address:'8.8.8.8',family:4}]}).market_public,request:SourceReadRequest={orgId:'org-pdf',connectionId:'conn-pdf',sourceKind:'market_public',scope:{urls:['https://public.example/evidence.pdf']},cursor:{previous:'complete'}};const result=await reader.read(request);assert.equal(result.status,'partial');if(result.status==='partial'){assert.equal(result.snapshots.length,1);assert.deepEqual(result.nextCursor,request.cursor);assert.equal(result.snapshots[0]!.coverage.status,'partial');assert.match(result.gaps.join(' '),/需OCR/);assert.match(await new SourceObjectStore(directory).readText({orgId:request.orgId,connectionId:request.connectionId,objectKey:result.snapshots[0]!.textObjectKey!,expectedHash:result.snapshots[0]!.textHash!}),/Actual source business evidence/);}}finally{await rm(directory,{recursive:true,force:true});}
});
test('source objects isolate tenant and connection, reject traversal/symlinks/tampering, and support concurrent immutable writes',async()=>{
 const directory=await root();try{const store=new SourceObjectStore(directory),objects=await Promise.all(Array.from({length:5},()=>store.put('org-a','conn-a',Buffer.from('original'),'原始正文')));assert.ok(objects.every(value=>value.objectKey===objects[0]!.objectKey));const saved=objects[0]!;assert.equal(await store.readText({orgId:'org-a',connectionId:'conn-a',objectKey:saved.textObjectKey,expectedHash:saved.textHash}),'原始正文');await assert.rejects(store.readText({orgId:'org-b',connectionId:'conn-a',objectKey:saved.textObjectKey,expectedHash:saved.textHash}),/SCOPE_MISMATCH/);await assert.rejects(store.put('../escape','conn-a',Buffer.from('x'),'x'),/SCOPE_INVALID/);await writeFile(join(directory,saved.textObjectKey),'篡改');await assert.rejects(store.readText({orgId:'org-a',connectionId:'conn-a',objectKey:saved.textObjectKey,expectedHash:saved.textHash}),/HASH_MISMATCH/);await assert.rejects(store.put('org-a','conn-a',Buffer.from('original'),'原始正文'),/HASH_MISMATCH/);await symlink(directory,join(directory,'symlink-org'));await assert.rejects(store.put('symlink-org','conn-a',Buffer.from('x'),'x'),/SCOPE_INVALID/);}finally{await rm(directory,{recursive:true,force:true});}
});
test('Drive recursively inventories approved folder, stores actual PPTX bytes/text, resumes changes and deduplicates',async()=>{
 const directory=await root(),state={version:'1',text:'用友方案'},fake=fakeDrive(state);try{const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>({accessToken:'test-oauth-token'}),fetch:fake.fetcher}).mac_drive;const first=await reader.read(driveRequest);changed(first);const snapshot=first.snapshots[0]!;assert.equal(snapshot.providerFileId,'nested-material');assert.deepEqual(snapshot.ancestorFolderIds,['authorized-root','nested-folder']);assert.deepEqual(snapshot.coverage.folder_ids,['authorized-root']);assert.ok(snapshot.textObjectKey&&snapshot.textHash);const store=new SourceObjectStore(directory);assert.match(await store.readText({orgId:driveRequest.orgId,connectionId:driveRequest.connectionId,objectKey:snapshot.textObjectKey!,expectedHash:snapshot.textHash!}),/用友方案/);assert.deepEqual(await store.readBytes({orgId:driveRequest.orgId,connectionId:driveRequest.connectionId,objectKey:snapshot.objectKey,expectedHash:snapshot.contentHash}),pptx('用友方案'));
 const second=await reader.read({...driveRequest,cursor:first.nextCursor});assert.equal(second.status,'no_change');assert.ok(fake.calls.some(url=>url.startsWith('/drive/v3/changes?')));state.version='2';state.text='致远方案';const third=await reader.read({...driveRequest,cursor:second.status==='no_change'?second.nextCursor:null});changed(third);assert.notEqual(third.snapshots[0]!.contentHash,snapshot.contentHash);assert.match(await store.readText({orgId:driveRequest.orgId,connectionId:driveRequest.connectionId,objectKey:snapshot.textObjectKey!,expectedHash:snapshot.textHash!}),/用友方案/);
 }finally{await rm(directory,{recursive:true,force:true});}
});
test('Drive deletion/move produces scoped tombstone and never downloads outside approved inventory',async()=>{
 const directory=await root(),state:{version:string;text:string;deleted?:boolean}={version:'1',text:'计划'},fake=fakeDrive(state);try{const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>'test-oauth-token',fetch:fake.fetcher}).mac_drive;const first=await reader.read(driveRequest);changed(first);state.deleted=true;const removed=await reader.read({...driveRequest,cursor:first.nextCursor});changed(removed);assert.equal(removed.snapshots.length,1);assert.equal(removed.snapshots[0]!.removed,true);assert.deepEqual(removed.snapshots[0]!.scopeFolderIds,['authorized-root']);assert.equal((removed.nextCursor as {files:object}).files&&Object.keys((removed.nextCursor as {files:object}).files).length,0);}finally{await rm(directory,{recursive:true,force:true});}
});
test('Drive expired cursor rescans authorized scope, while failed/unsupported reads hold original complete watermark',async()=>{
 const directory=await root(),state:{version:string;text:string;expireCursor?:boolean;failDownload?:boolean;unsupported?:boolean;failList?:boolean}={version:'1',text:'计划'},fake=fakeDrive(state);try{const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>'test-oauth-token',fetch:fake.fetcher}).mac_drive;const first=await reader.read(driveRequest);changed(first);state.expireCursor=true;state.version='2';state.text='新计划';const resumed=await reader.read({...driveRequest,cursor:first.nextCursor});changed(resumed);assert.ok(fake.calls.filter(url=>url.startsWith('/drive/v3/changes/startPageToken')).length>=2);
 state.version='3';state.failDownload=true;const incomplete=await reader.read({...driveRequest,cursor:resumed.nextCursor});assert.equal(incomplete.status,'partial');if(incomplete.status==='partial'){assert.deepEqual(incomplete.nextCursor,resumed.nextCursor);assert.equal(incomplete.snapshots.length,0);assert.ok(incomplete.gaps.length);}state.failDownload=false;state.unsupported=true;const unsupported=await reader.read({...driveRequest,cursor:resumed.nextCursor});assert.equal(unsupported.status,'partial');state.failList=true;const failed=await reader.read({...driveRequest,cursor:resumed.nextCursor});assert.equal(failed.status,'failed');}finally{await rm(directory,{recursive:true,force:true});}
});
test('Drive OAuth refresh uses secret-bound fixed token endpoint; unauthorized and missing credentials report real failure',async()=>{
 const directory=await root(),fake=fakeDrive({version:'1',text:'方案'});try{let refreshes=0;const fetcher=(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>{if(String(input)==='https://oauth2.googleapis.com/token'){refreshes++;assert.equal(init?.method,'POST');assert.equal(new URLSearchParams(String(init?.body)).get('grant_type'),'refresh_token');return json({access_token:'test-oauth-token',token_type:'Bearer'});}return fake.fetcher(input,init);}) as typeof fetch;const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>({kind:'drive_oauth',clientId:'private-id',clientSecret:'private-secret',refreshToken:'private-refresh',expiresAt:'2026-01-01T00:00:00Z'}),fetch:fetcher}).mac_drive;const result=await reader.read(driveRequest);changed(result);assert.equal(refreshes,1);assert.ok(!JSON.stringify(result).includes('private-secret'));
 const missing=await reader.read({...driveRequest,credentialRef:undefined} as unknown as SourceReadRequest);assert.equal(missing.status,'failed');if(missing.status==='failed')assert.equal(missing.errorCode,'NOT_CONFIGURED');const bad=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>'invalid-token',fetch:fakeDrive({version:'1',text:'x',authFailure:true}).fetcher}).mac_drive;const unauthorized=await bad.read(driveRequest);assert.equal(unauthorized.status,'failed');if(unauthorized.status==='failed')assert.equal(unauthorized.errorCode,'AUTH_REQUIRED');}finally{await rm(directory,{recursive:true,force:true});}
});
test('Drive incomplete search and a revision changing during download cannot advance the complete watermark',async()=>{
 const directory=await root();try{const state={version:'1',text:'资料'},fake=fakeDrive(state),limited=(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>new URL(String(input)).pathname.endsWith('/files')?json({files:[],incompleteSearch:true}):fake.fetcher(input,init)) as typeof fetch;
 const incomplete=await createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>'test-oauth-token',fetch:limited}).mac_drive.read(driveRequest);assert.equal(incomplete.status,'failed');if(incomplete.status==='failed')assert.equal(incomplete.errorCode,'SCOPE_INCOMPLETE');
 const racing=(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>{const response=await fake.fetcher(input,init);const url=new URL(String(input));if(url.pathname.endsWith('/files/nested-material')&&url.searchParams.get('alt')==='media')state.version='2';return response;}) as typeof fetch,request={...driveRequest,cursor:{previous:'verified-watermark'}};
 const race=await createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>'test-oauth-token',fetch:racing}).mac_drive.read(request);assert.equal(race.status,'partial');if(race.status==='partial'){assert.deepEqual(race.nextCursor,request.cursor);assert.equal(race.snapshots.length,0);}
 assert.throws(()=>createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>null,maxBytes:NaN}),/SOURCE_LIMIT_INVALID/);
 }finally{await rm(directory,{recursive:true,force:true});}
});
test('public sources reject private DNS, mapped IPs, secret query strings, and redirects outside configured URL scope',async()=>{
 for(const address of ['127.0.0.1','10.0.0.1','172.16.1.1','192.168.1.1','169.254.169.254','100.64.0.1','::1','fc00::1','::ffff:127.0.0.1','::ffff:7f00:1'])assert.equal(isPublicSourceAddress(address),false,address);assert.equal(isPublicSourceAddress('8.8.8.8'),true);assert.equal(isPublicSourceAddress('2606:4700:4700::1111'),true);
 const directory=await root();try{let requests=0;const fetcher=(async()=>{requests++;return new Response(null,{status:302,headers:{location:'https://outside.example/secret'}});}) as typeof fetch;const request:SourceReadRequest={orgId:'test-org',connectionId:'test-public',sourceKind:'market_public',scope:{urls:['https://public.example/article']},cursor:{old:true}};
 const privateReader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>null,fetch:fetcher,resolveHost:async()=>[{address:'127.0.0.1',family:4}]}).market_public;const privateResult=await privateReader.read(request);assert.equal(privateResult.status,'partial');assert.equal(requests,0);const publicReader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>null,fetch:fetcher,resolveHost:async()=>[{address:'8.8.8.8',family:4}]}).market_public;const redirected=await publicReader.read(request);assert.equal(redirected.status,'partial');if(redirected.status==='partial')assert.deepEqual(redirected.nextCursor,request.cursor);assert.equal(requests,1);const secret=await publicReader.read({...request,scope:{urls:['https://public.example/article?access_token=private']}});assert.equal(secret.status,'failed');assert.equal(requests,1);}finally{await rm(directory,{recursive:true,force:true});}
});
test('public HTML source stores bounded original and cleaned evidence text and detects real body changes',async()=>{
 const directory=await root();try{let content='<html><title>市场观察</title><body><script>secret script</script><h1>业务变化</h1><p>需求 &amp; 推广</p></body></html>';const reader=createRuntimeSourceReaders({sourceRoot:directory,resolveSecret:async()=>null,fetch:(async()=>new Response(content,{headers:{'content-type':'text/html','last-modified':'Sun, 04 Oct 2026 00:00:00 GMT'}})) as typeof fetch,resolveHost:async()=>[{address:'8.8.8.8',family:4}]}).market_public;const request:SourceReadRequest={orgId:'org-public',connectionId:'conn-public',sourceKind:'market_public',scope:{urls:['https://public.example/article']},cursor:null};const first=await reader.read(request);changed(first);const source=first.snapshots[0]!,store=new SourceObjectStore(directory),text=await store.readText({orgId:request.orgId,connectionId:request.connectionId,objectKey:source.textObjectKey!,expectedHash:source.textHash!});assert.match(text,/业务变化/);assert.match(text,/需求 & 推广/);assert.doesNotMatch(text,/secret script/);assert.equal(first.snapshots[0]!.title,'市场观察');const repeat=await reader.read({...request,cursor:first.nextCursor});assert.equal(repeat.status,'no_change');content=content.replace('业务变化','新市场信号');const latest=await reader.read({...request,cursor:repeat.status==='no_change'?repeat.nextCursor:null});changed(latest);assert.notEqual(latest.snapshots[0]!.contentHash,source.contentHash);}finally{await rm(directory,{recursive:true,force:true});}
});
