import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createTestDatabase,DEMO_ORG_ID,DEMO_OWNER_ID,type Database} from '@boran/db';
import {stableHash,type ServiceContext} from '@boran/domain/core';
import {createPolicy,activatePolicy,createExecutionAction,assertActionExecutable,claimExecutionAction} from '@boran/domain/execution';
import {createPlatformAdapter,createPlatformRegistry,getPlatformDescriptor,type PlatformHooks} from '@boran/connectors';
import {createBrowserService,type BrowserServiceDependencies} from '../src/service';
import {browserDispatchEnvironment,queueBrowserActions,dispatchBrowserCommands,startBrowserDispatcher,type BrowserDispatchReadiness} from '../src/dispatcher';
import {dispatchBrowserWork} from '../../worker/src/browser-dispatch';

const configured:BrowserDispatchReadiness={orgIds:[DEMO_ORG_ID],identityConfigured:true,configuredPlatforms:['wechat_mp'],writeEnabled:true,publishEnabled:true,adsWriteEnabled:true};
const context=(db:Database,mode:'mock'|'live'='live'):ServiceContext=>({db,orgId:DEMO_ORG_ID,actorId:DEMO_OWNER_ID,actorType:'user',roles:['owner'],mode});
async function account(ctx:ServiceContext){const id=randomUUID(),connection=randomUUID(),external=`qa-${id}`,profile=randomUUID(),profileVersion=randomUUID();
 await ctx.db.query("INSERT INTO connections(id,org_id,provider,account_external_id,display_name,timezone,currency,read_mode,access_status,health,capabilities_verified_at) VALUES($1,$2,$3,$4,'QA injected transport account','Asia/Shanghai','CNY',$5,'connected','healthy',now())",[connection,ctx.orgId,ctx.mode==='mock'?'mock':'wechat_mp',external,ctx.mode==='mock'?'mock':'authorized_browser']);
 await ctx.db.query("INSERT INTO platform_accounts(id,org_id,connection_id,provider,channel_id,account_external_id,display_name,timezone,enabled,session_status,adapter_version,last_session_verified_at) VALUES($1,$2,$3,'wechat_mp','wechat_mp',$4,'QA injected transport account','Asia/Shanghai',true,'active','qa-v1',now())",[id,ctx.orgId,connection,external]);
 await ctx.db.query("INSERT INTO platform_profiles(id,org_id,platform_account_id,name) VALUES($1,$2,$3,'QA profile')",[profile,ctx.orgId,id]);
 await ctx.db.query("INSERT INTO platform_profile_versions(id,org_id,profile_id,audience,allowed_formats,rules_json,rules_source_urls,rules_checked_at,payload_hash) VALUES($1,$2,$3,'QA only','{article}','{}','{}',now(),$4)",[profileVersion,ctx.orgId,profile,stableHash({qa:true})]);
 return{id,connection,external,profileVersion};
}
async function intent(ctx:ServiceContext,a:Awaited<ReturnType<typeof account>>,scheduled=new Date(Date.now()-1000).toISOString(),windows:unknown[]=[{days:[0,1,2,3,4,5,6],start:'00:00',end:'24:00'}]){
 const item=randomUUID(),version=randomUUID(),variant=randomUUID(),body={title:'QA synthetic publication',body:randomUUID()},hash=stableHash(body);
 await ctx.db.query("INSERT INTO content_items(id,org_id,kind,business_line,owner_user_id,title) VALUES($1,$2,'article','shared',$3,'QA synthetic publication')",[item,ctx.orgId,ctx.actorId]);
 await ctx.db.query("INSERT INTO content_versions(id,org_id,content_item_id,body_json,claim_ids,payload_hash,review_status,warnings) VALUES($1,$2,$3,$4,'{}',$5,'approved','[]')",[version,ctx.orgId,item,JSON.stringify(body),hash]);
 await ctx.db.query("INSERT INTO content_variants(id,org_id,mother_content_version_id,content_version_id,platform_account_id,platform_profile_version_id,format,validation_status,validated_at,validated_payload_hash) VALUES($1,$2,$3,$3,$4,$5,'article','passed',now(),$6)",[variant,ctx.orgId,version,a.id,a.profileVersion,hash]);
 const target={platform_account_id:a.id,content_variant_id:variant,business_line:'shared'};
 const policy=await createPolicy(ctx,{name:'QA exact persisted scope',businessScope:{business_lines:['shared']},accountIds:[a.id],allowedActions:['external.publish'],publishFrequency:{daily_max:100,weekly_max:100,min_interval_minutes:0},publishWindows:windows,stopConditions:{max_errors:5}});
 const policyVersion=String((await ctx.db.query('SELECT id FROM policy_versions WHERE org_id=$1 AND policy_id=$2',[ctx.orgId,policy.id])).rows[0]!.id);
 await activatePolicy(ctx,String(policy.id),policyVersion,1);
 const action=await createExecutionAction(ctx,{idempotencyKey:randomUUID(),actionType:'external.publish',target,payload:body,beforeSnapshot:{},versionId:version,policyVersionId:policyVersion});
 const job=randomUUID();await ctx.db.query("INSERT INTO publish_jobs(id,org_id,execution_action_id,platform_account_id,content_variant_id,scheduled_at,schedule_slot_key) VALUES($1,$2,$3,$4,$5,$6,$7)",[job,ctx.orgId,action.id,a.id,variant,scheduled,randomUUID()]);
 return{actionId:String(action.id),jobId:job,hash,policyId:String(policy.id)};
}
const row=async(db:Database,table:'browser_commands'|'execution_actions'|'publish_jobs',id:string)=>(await db.query(`SELECT * FROM ${table} WHERE id=$1`,[id])).rows[0]!;
function dependencies(ctx:ServiceContext,hooks:PlatformHooks):BrowserServiceDependencies{return{adapters:new Map([['wechat_mp',createPlatformAdapter('wechat_mp',{mode:'live',hooks})]]),authorizeAction:async(c,tx,id)=>{await assertActionExecutable(c,tx,id);},withProfile:async(_input,run)=>run({qaInjectedBrowser:true})};}
function hooksFor(ctx:ServiceContext,hashes:Map<string,string>,counters:{writes:number;reads:number},uncertain=false):PlatformHooks{
 const proof=(c:{externalAccountId:string;adapterVersion:string})=>({verified:true as const,externalAccountId:c.externalAccountId,adapterVersion:c.adapterVersion,evidenceRef:'qa/injected-proof',capturedAt:new Date().toISOString(),kind:'api_readback' as const,capabilities:[...getPlatformDescriptor('wechat_mp').requiredCapabilities],labelsVerified:true});
 return{probe:async c=>proof(c),sessionVerify:async c=>{counters.reads++;return{status:'verified',evidence:proof(c)};},publish:async(c,command)=>{await c.assertLease();counters.writes++;return{status:'submitted',externalId:`qa-${command.actionId}`};},readback:async(c,command)=>{if(uncertain)throw new Error('lost readback');return{status:'verified',evidence:{...proof(c),contentHash:hashes.get(command.actionId!)!},data:{external_id:`qa-${command.actionId}`,published_url:`https://mp.weixin.qq.com/s/qa-${command.actionId}`,review_status:'approved'}};}};
}

test('durable dispatcher removes queued integration gaps without crossing deployment organization bindings',async t=>{
 const db=await createTestDatabase();try{const ctx=context(db,'mock'),a=await account(ctx),service=createBrowserService(ctx,{adapters:createPlatformRegistry({mode:'mock'})});
 await t.test('server deployment configuration cannot use body/token organization claims',()=>{assert.deepEqual(browserDispatchEnvironment({BORAN_MODE:'mock'}).readiness.orgIds,[DEMO_ORG_ID]);assert.throws(()=>browserDispatchEnvironment({BORAN_MODE:'live',BROWSER_DISPATCH_ORGS:DEMO_ORG_ID}),{code:'DISPATCH_ORGANIZATION_FORBIDDEN'});const email='worker@qa.iam.gserviceaccount.com';assert.equal(browserDispatchEnvironment({BORAN_MODE:'live',BROWSER_OIDC_AUDIENCE:'https://qa.invalid',BROWSER_SERVICE_ORGS:JSON.stringify({[email]:[DEMO_ORG_ID]})}).readiness.identityConfigured,true);});
 await t.test('durable mock commands cannot become live commands after changing deployment mode',async()=>{const key=randomUUID();const input={command_type:'session_verify' as const,platform_account_id:a.id,adapter_version:'qa-v1',idempotency_key:key,input_ref:{}};const command=await service.enqueue(input);const live=createBrowserService({...ctx,mode:'live'},{adapters:new Map()});await assert.rejects(()=>live.claim(command.id,'qa-cross-mode'),{code:'command_mode_mismatch'});await assert.rejects(()=>live.enqueue(input),{code:'idempotency_conflict'});await service.cancel(command.id);});
 await t.test('session verification stops as blocked with durable missing capabilities, never fabricated success',async()=>{const command=await service.enqueue({command_type:'session_verify',platform_account_id:a.id,adapter_version:'qa-v1',idempotency_key:randomUUID(),input_ref:{}});const outcome=await dispatchBrowserCommands(ctx,{...configured,identityConfigured:false,configuredPlatforms:[],writeEnabled:false},{adapters:createPlatformRegistry({mode:'mock'})},'qa-dispatch');assert.equal(outcome.blocked,1);const saved=await row(db,'browser_commands',command.id);assert.equal(saved.state,'blocked');assert.ok((saved.last_error as {missing_capabilities:string[]}).missing_capabilities.includes('service_oidc'));assert.equal((saved.result_ref as {verified:boolean}).verified,false);assert.equal((await db.query("SELECT id FROM outbox_events WHERE event_type='alert.browser_integration_required'")).rows.length,1);});
 await t.test('the worker consumes due persisted actions into blocked jobs when real integrations are absent',async()=>{const action=await intent(ctx,a);const outcome=await dispatchBrowserWork(db,{mode:'mock',readiness:{...configured,identityConfigured:false,configuredPlatforms:[],writeEnabled:false}});assert.equal(outcome.blocked,1);assert.equal((await row(db,'execution_actions',action.actionId)).state,'blocked');assert.equal((await row(db,'publish_jobs',action.jobId)).delivery_state,'blocked');assert.equal((await db.query("SELECT id FROM outbox_events WHERE aggregate_id=$1 AND event_type='execution.queued' AND dispatched_at IS NULL",[action.actionId])).rows.length,0);assert.equal((await db.query("SELECT id FROM browser_commands WHERE execution_action_id=$1",[action.actionId])).rows.length,0);});
 await t.test('future jobs remain scheduled until due, and other organizations cannot be polled',async()=>{const future=await intent(ctx,a,new Date(Date.now()+86400000).toISOString());assert.equal((await queueBrowserActions(ctx,configured,{adapters:createPlatformRegistry({mode:'mock'})})).blocked,0);assert.equal((await row(db,'publish_jobs',future.jobId)).delivery_state,'scheduled');await assert.rejects(()=>dispatchBrowserCommands({...ctx,orgId:randomUUID()},configured,{adapters:new Map()},'qa-foreign'),{code:'DISPATCH_ORGANIZATION_FORBIDDEN'});});
 await t.test('the actual background timer consumes the durable queue',async()=>{const command=await service.enqueue({command_type:'session_verify',platform_account_id:a.id,adapter_version:'qa-v1',idempotency_key:randomUUID(),input_ref:{}});const running=startBrowserDispatcher({db,mode:'mock',readiness:{...configured,identityConfigured:false,configuredPlatforms:[]},dependencies:{adapters:createPlatformRegistry({mode:'mock'})},workerId:'qa-background',intervalMs:10});try{for(let i=0;i<50&&(await service.get(command.id)).state==='queued';i++)await new Promise(resolve=>setTimeout(resolve,10));assert.equal((await service.get(command.id)).state,'blocked');}finally{await running.stop();}});
 }finally{await db.close();}
});

test('configured polling executes only authorized injected readbacks, with separate action/browser fences',async t=>{
 const db=await createTestDatabase();try{const ctx=context(db),a=await account(ctx);await db.query('UPDATE organizations SET write_enabled=true WHERE id=$1',[ctx.orgId]);const hashes=new Map<string,string>(),counters={writes:0,reads:0},deps=dependencies(ctx,hooksFor(ctx,hashes,counters));
 await t.test('read-only verification runs when deployment writes are disabled',async()=>{const service=createBrowserService(ctx,deps);const command=await service.enqueue({command_type:'session_verify',platform_account_id:a.id,adapter_version:'qa-v1',idempotency_key:randomUUID(),input_ref:{}});assert.equal((await dispatchBrowserCommands(ctx,{...configured,writeEnabled:false,publishEnabled:false},deps,'qa-read')).executed,1);assert.equal((await service.get(command.id)).state,'succeeded');assert.equal(counters.reads,1);assert.equal(counters.writes,0);const verified=(await db.query('SELECT session_status,last_session_verified_at,session_version FROM platform_accounts WHERE id=$1',[a.id])).rows[0]!;assert.equal(verified.session_status,'active');assert.ok(verified.last_session_verified_at);assert.equal(Number(verified.session_version),1);});
 await t.test('two worker iterations queue one command; parallel dispatchers submit at most once and update the job ledger',async()=>{const i=await intent(ctx,a);hashes.set(i.actionId,i.hash);const queued=await Promise.all([queueBrowserActions(ctx,configured,deps),queueBrowserActions(ctx,configured,deps)]);assert.equal(queued.reduce((n,r)=>n+r.queued,0),1);const commands=(await db.query("SELECT id FROM browser_commands WHERE execution_action_id=$1",[i.actionId])).rows;assert.equal(commands.length,1);await Promise.all([dispatchBrowserCommands(ctx,configured,deps,'qa-node-a'),dispatchBrowserCommands(ctx,configured,deps,'qa-node-b')]);assert.equal(counters.writes,1);assert.equal((await row(db,'execution_actions',i.actionId)).state,'succeeded');assert.equal((await row(db,'publish_jobs',i.jobId)).delivery_state,'published_verified');assert.equal((await row(db,'publish_jobs',i.jobId)).verification_status,'verified');assert.equal((await row(db,'browser_commands',String(commands[0]!.id))).state,'succeeded');assert.equal((await dispatchBrowserCommands(ctx,configured,deps,'qa-repeat')).executed,0);assert.equal(counters.writes,1);});
 await t.test('unknown receipts and expired action claims never trigger another external write',async()=>{const i=await intent(ctx,a);hashes.set(i.actionId,i.hash);const uncertain=dependencies(ctx,hooksFor(ctx,hashes,counters,true));await queueBrowserActions(ctx,configured,uncertain);await dispatchBrowserCommands(ctx,configured,uncertain,'qa-uncertain');assert.equal((await row(db,'execution_actions',i.actionId)).state,'unknown');assert.equal((await row(db,'publish_jobs',i.jobId)).delivery_state,'unknown');const count=counters.writes;assert.equal((await queueBrowserActions(ctx,configured,uncertain)).queued,0);assert.equal((await dispatchBrowserCommands(ctx,configured,uncertain,'qa-no-retry')).executed,1);assert.equal(counters.writes,count);assert.equal((await row(db,'execution_actions',i.actionId)).state,'unknown');
 const crashed=await intent(ctx,a);hashes.set(crashed.actionId,crashed.hash);await queueBrowserActions(ctx,configured,deps);await claimExecutionAction(ctx,crashed.actionId,'qa-crashed',30);await db.query("UPDATE execution_actions SET lease_until=now()-interval '1 second' WHERE id=$1",[crashed.actionId]);await dispatchBrowserCommands(ctx,configured,deps,'qa-recovery');assert.equal((await row(db,'execution_actions',crashed.actionId)).state,'unknown');assert.equal((await row(db,'publish_jobs',crashed.jobId)).delivery_state,'unknown');assert.equal(counters.writes,count);});
 await t.test('a disabled global write switch stops queued publishing before any adapter mutation',async()=>{const i=await intent(ctx,a);hashes.set(i.actionId,i.hash);await queueBrowserActions(ctx,configured,deps);const before=counters.writes;const outcome=await dispatchBrowserCommands(ctx,{...configured,writeEnabled:false},deps,'qa-stop');assert.equal(outcome.blocked,1);assert.equal(counters.writes,before);assert.equal((await row(db,'execution_actions',i.actionId)).state,'blocked');assert.equal((await row(db,'publish_jobs',i.jobId)).delivery_state,'blocked');});
 await t.test('delayed publication rechecks the current account-local approved window',async()=>{const at=new Date(),parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(at);const minute=Number(parts.find(p=>p.type==='hour')!.value)*60+Number(parts.find(p=>p.type==='minute')!.value);const time=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;const i=await intent(ctx,a,new Date(at.getTime()-1000).toISOString(),[{days:[0,1,2,3,4,5,6],start:time(Math.max(0,minute-1)),end:time(Math.min(1440,minute+2))}]);hashes.set(i.actionId,i.hash);assert.equal((await queueBrowserActions(ctx,configured,deps)).queued,1);const before=counters.writes,moved={...ctx,now:()=>new Date(at.getTime()+300000)};await dispatchBrowserCommands(moved,configured,deps,'qa-delayed');assert.equal(counters.writes,before);assert.equal((await row(db,'execution_actions',i.actionId)).state,'blocked');assert.equal((await row(db,'publish_jobs',i.jobId)).delivery_state,'blocked');assert.equal((await row(db,'execution_actions',i.actionId)).last_error&&((await row(db,'execution_actions',i.actionId)).last_error as {code:string}).code,'PUBLISH_WINDOW_CLOSED');});
 await t.test('polling preserves per-account exclusion and the global concurrency limit of two',async()=>{const b=await account(ctx),c=await account(ctx);let active=0,maximum=0;const accounts=new Set<string>();const base=hooksFor(ctx,hashes,counters);const concurrent=dependencies(ctx,{...base,sessionVerify:async current=>{assert.equal(accounts.has(current.accountId),false);accounts.add(current.accountId);active++;maximum=Math.max(maximum,active);await new Promise(resolve=>setTimeout(resolve,30));active--;accounts.delete(current.accountId);return{status:'verified',evidence:{verified:true,externalAccountId:current.externalAccountId,evidenceRef:'qa/concurrent-readback',capturedAt:new Date().toISOString(),kind:'api_readback'}};}});const service=createBrowserService(ctx,concurrent);for(const id of [a.id,a.id,b.id,c.id])await service.enqueue({command_type:'session_verify',platform_account_id:id,adapter_version:'qa-v1',idempotency_key:randomUUID(),input_ref:{}});const result=await dispatchBrowserCommands(ctx,configured,concurrent,'qa-capacity');assert.equal(maximum,2);assert.ok(result.deferred>=1);assert.equal(active,0);await dispatchBrowserCommands(ctx,configured,concurrent,'qa-capacity');assert.equal((await db.query("SELECT id FROM browser_commands WHERE state IN ('queued','running')")).rows.length,0);});
 }finally{await db.close();}
});
