import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createTestDatabase,DEMO_ORG_ID,DEMO_OWNER_ID,type Database} from '@boran/db';
import type {ServiceContext} from '@boran/domain/core';
import {preflightImport,commitImport,getAdMetrics,refreshBaiduReadiness,type AdReportType} from '@boran/domain/ads';
import {createReportSnapshot,getReports,calculateSeoMetrics,getSevenDayCompleteness,enqueueReportNotifications,processNotification,archiveReportToDrive,advertisingRetention,type DriveArchiveAdapter,type NotificationAdapter} from '@boran/domain/reporting';
import {createBaiduAdapter} from '@boran/connectors/baidu';

function context(db:Database):ServiceContext{return{db,orgId:DEMO_ORG_ID,actorId:DEMO_OWNER_ID,roles:['owner','marketer'],mode:'mock'};}
async function connection(ctx:ServiceContext,currency='CNY') {const id=randomUUID(),external=`qa-${randomUUID()}`;await ctx.db.query("INSERT INTO connections(id,org_id,provider,account_external_id,display_name,timezone,currency,read_mode,enabled_for_reporting,authoritative_report_type) VALUES($1,$2,'mock',$3,'Anonymous QA account','Asia/Shanghai',$4,'mock',true,'campaign_daily')",[id,ctx.orgId,external,currency]);return{id,external,currency};}
function rows(external:string,level='campaign',currency='CNY') {return[{business_date:'2026-09-30',account_id:external,entity_level:level,entity_id:`${level}-a`,currency,conversion_definition:'platform-form',device:'all',impressions:100,clicks:10,spend_minor:10_000_001,platform_conversions:'0.1250'},{business_date:'2026-10-01',account_id:external,entity_level:level,entity_id:`${level}-a`,currency,conversion_definition:'platform-form',device:'all',impressions:200,clicks:20,spend_minor:20_000_002,platform_conversions:'0.2500'}];}
async function ingest(ctx:ServiceContext,c:{id:string;external:string;currency:string},values:Record<string,unknown>[],options:{type?:AdReportType;complete?:boolean;watermark?:string}={}) {const preflight=await preflightImport(ctx,{connectionId:c.id,reportType:options.type??'campaign_daily',windowStart:'2026-09-30',windowEnd:'2026-10-01',currency:c.currency,timezone:'Asia/Shanghai',rows:values,sourceWatermark:options.watermark??new Date().toISOString()});assert.equal(preflight.state,'validated');await commitImport(ctx,preflight.id,{expectedFileHash:preflight.fileHash,confirmCompleteWindow:options.complete??true,revisionPolicy:'upsert_by_natural_key'});return preflight;}
async function due(ctx:ServiceContext,id:string,event:string) {await ctx.db.query("UPDATE outbox_events SET next_attempt_at='2000-01-01T00:00:00Z' WHERE org_id=$1 AND aggregate_id=$2 AND event_type=$3",[ctx.orgId,id,event]);}

test('QA ads: authoritative grain, microCNY precision, missing values and isolated currencies',async t=>{
 const db=await createTestDatabase();try{const ctx=context(db),c=await connection(ctx);await ingest(ctx,c,rows(c.external));await ingest(ctx,c,rows(c.external,'keyword').map(row=>({...row,spend_minor:999_999_999})),{type:'keyword_daily'});
 await t.test('campaign totals never add subordinate keyword totals and preserve every microCNY',async()=>{const result=await getAdMetrics(ctx,{start:'2026-09-30',end:'2026-10-01'});assert.equal(result.spendMinor,30_000_003);assert.equal(result.accounts[0]!.impressions,300);assert.equal(result.accounts[0]!.clicks,30);assert.equal(result.accounts[0]!.platformConversions,0.375);assert.equal(result.accounts[0]!.realLeads,null);assert.equal(result.accounts[0]!.paidCplMinor,null);assert.equal(result.accounts[0]!.optimizationEligible,false);assert.deepEqual(result.accounts[0]!.sourceKinds,['historical_import']);});
 await t.test('one missing date makes totals unavailable while preserving observed spend',async()=>{const result=await getAdMetrics(ctx,{start:'2026-09-30',end:'2026-10-02'});assert.equal(result.quality,'partial');assert.equal(result.spendMinor,null);assert.equal(result.accounts[0]!.observedSpendMinor,30_000_003);assert.equal(result.accounts[0]!.daily[2]!.quality,'missing');assert.equal(result.accounts[0]!.daily[2]!.spendMinor,null);assert.equal(result.accounts[0]!.daily[2]!.platformConversions,null);});
 await t.test('missing conversion evidence remains null, not zero',async()=>{const revised=rows(c.external).map(row=>({...row,platform_conversions:null}));await ingest(ctx,c,revised,{watermark:new Date(Date.now()+1000).toISOString()});const result=await getAdMetrics(ctx,{start:'2026-09-30',end:'2026-10-01'});assert.equal(result.accounts[0]!.platformConversions,null);assert.equal(result.spendMinor,30_000_003);});
 await t.test('currencies are never silently combined or converted',async()=>{const usd=await connection(ctx,'USD');await ingest(ctx,usd,rows(usd.external,'campaign','USD'));const result=await getAdMetrics(ctx,{start:'2026-09-30',end:'2026-10-01'});assert.equal(result.currency,null);assert.equal(result.spendMinor,null);assert.equal(result.accounts.length,2);});
 }finally{await db.close();}
});

test('QA CSV: confirmation, invalid values, revisions and immutable report snapshots',async t=>{
 const db=await createTestDatabase();try{const ctx=context(db),c=await connection(ctx),watermark=new Date().toISOString();const first=await ingest(ctx,c,rows(c.external),{complete:false,watermark});
 await t.test('unconfirmed CSV windows remain partial and same content is idempotent',async()=>{const metrics=await getAdMetrics(ctx,{start:'2026-09-30',end:'2026-10-01'});assert.equal(metrics.quality,'partial');assert.equal(metrics.spendMinor,null);const duplicate=await preflightImport(ctx,{connectionId:c.id,reportType:'campaign_daily',windowStart:'2026-09-30',windowEnd:'2026-10-01',currency:'CNY',timezone:'Asia/Shanghai',rows:rows(c.external),sourceWatermark:watermark});assert.equal(duplicate.id,first.id);assert.equal(duplicate.duplicate,true);});
 await t.test('missing dates cannot be confirmed complete and unsafe amounts are rejected',async()=>{const missing=await preflightImport(ctx,{connectionId:c.id,reportType:'campaign_daily',windowStart:'2026-09-30',windowEnd:'2026-10-01',currency:'CNY',timezone:'Asia/Shanghai',rows:rows(c.external).slice(0,1)});assert.equal(missing.quality,'partial');await assert.rejects(()=>commitImport(ctx,missing.id,{expectedFileHash:missing.fileHash,confirmCompleteWindow:true,revisionPolicy:'upsert_by_natural_key'}),{code:'INCOMPLETE_WINDOW'});for(const spend of [-1,Number.MAX_SAFE_INTEGER+1,0.000001]){const bad=await preflightImport(ctx,{connectionId:c.id,reportType:'campaign_daily',windowStart:'2026-09-30',windowEnd:'2026-10-01',currency:'CNY',timezone:'Asia/Shanghai',rows:rows(c.external).map(row=>({...row,spend_minor:spend}))});assert.equal(bad.state,'rejected');}});
 const snapshot=await createReportSnapshot(ctx,{kind:'daily',start:'2026-09-30',end:'2026-10-01',body:{facts:[{fabricated:true}],actions:[{fakeSuccess:true}]}});
 await t.test('same-watermark conflicting revisions stop and never alter the earlier snapshot',async()=>{const conflict=await preflightImport(ctx,{connectionId:c.id,reportType:'campaign_daily',windowStart:'2026-09-30',windowEnd:'2026-10-01',currency:'CNY',timezone:'Asia/Shanghai',rows:rows(c.external).map(row=>({...row,spend_minor:row.spend_minor+1})),sourceWatermark:watermark});await assert.rejects(()=>commitImport(ctx,conflict.id,{expectedFileHash:conflict.fileHash,confirmCompleteWindow:true,revisionPolicy:'upsert_by_natural_key'}),{code:'SOURCE_WATERMARK_CONFLICT'});assert.equal((await getAdMetrics(ctx,{start:'2026-09-30',end:'2026-10-01'})).accounts[0]!.observedSpendMinor,30_000_003);});
 await t.test('newer revisions upsert natural keys and produce a new report, retaining prior report evidence',async()=>{await ingest(ctx,c,rows(c.external).map(row=>({...row,spend_minor:row.spend_minor+1})),{watermark:new Date(Date.parse(watermark)+1000).toISOString()});const next=await createReportSnapshot(ctx,{kind:'daily',start:'2026-09-30',end:'2026-10-01'});assert.equal(next.revision,snapshot.revision+1);assert.notEqual(next.id,snapshot.id);assert.equal((await createReportSnapshot(ctx,{kind:'daily',start:'2026-09-30',end:'2026-10-01'})).id,next.id);assert.equal((await db.query('SELECT id FROM ad_daily_facts WHERE connection_id=$1',[c.id])).rows.length,2);const reports=(await getReports(ctx)).reports;assert.equal(reports.length,2);const old=reports.find(row=>row.id===snapshot.id)!;assert.equal((old.metrics_json as {spendMinor:number|null}).spendMinor,null);assert.equal(JSON.stringify(old.body_json).includes('fabricated'),false);assert.equal(JSON.stringify(old.body_json).includes('fakeSuccess'),false);});
 }finally{await db.close();}
});

test('QA reports: actual readback required, uncertain archive/notification receipts reconcile before retries',async t=>{
 const db=await createTestDatabase();try{const ctx=context(db),report=await createReportSnapshot(ctx,{kind:'daily',start:'2026-10-01',end:'2026-10-01'});let stored:string|null=null,writeCount=0,validReadback=false;const drive:DriveArchiveAdapter={mode:'mock',findByIdempotencyKey:async()=>stored?{fileId:'qa-file'}:null,reconcile:async()=>({state:'unknown'}),write:async input=>{writeCount++;stored=input.content;return{fileId:'qa-file'};},read:async()=>({content:validReadback?stored!:'different bytes',revision:'qa-r1'})};
 await t.test('write acknowledgement alone cannot mark a report archived; failed receipt remains durable',async()=>{assert.equal((await archiveReportToDrive(ctx,report.id,drive)).state,'failed');const saved=(await db.query('SELECT archive_status,drive_file_id FROM report_snapshots WHERE id=$1',[report.id])).rows[0]!;assert.equal(saved.archive_status,'failed');assert.equal(saved.drive_file_id,null);assert.equal((await db.query("SELECT id FROM outbox_events WHERE aggregate_id=$1 AND event_type='report.archive' AND dispatched_at IS NULL",[report.id])).rows.length,1);});
 await t.test('recovery finds the existing file and verifies exact content without another write',async()=>{validReadback=true;await due(ctx,report.id,'report.archive');const result=await archiveReportToDrive(ctx,report.id,drive);assert.equal(result.state,'succeeded');assert.equal('realAcceptance' in result?result.realAcceptance:false,false);assert.equal(writeCount,1);assert.equal((await archiveReportToDrive(ctx,report.id,drive)).duplicate,true);});
 const ids=await enqueueReportNotifications(ctx,report.id,[{channel:'email',recipientRef:'email:qa-recipient'}]);assert.deepEqual((await enqueueReportNotifications(ctx,report.id,[{channel:'email',recipientRef:'email:qa-recipient'}])).ids,ids.ids);let sends=0,reconcileState:'unknown'|'delivered'='unknown';const notifier:NotificationAdapter={mode:'mock',send:async()=>{sends++;throw new Error('acknowledgement lost after provider accepted');},reconcile:async()=>({state:reconcileState,providerMessageId:reconcileState==='delivered'?'qa-message':null})};
 await t.test('unknown notification receipt never triggers a blind resend and can recover from provider readback',async()=>{const id=ids.ids[0]!;await due(ctx,id,'notification.deliver');assert.equal((await processNotification(ctx,id,notifier)).state,'failed');await due(ctx,id,'notification.deliver');assert.equal((await processNotification(ctx,id,notifier)).state,'failed');assert.equal(sends,1);reconcileState='delivered';await due(ctx,id,'notification.deliver');assert.equal((await processNotification(ctx,id,notifier)).state,'succeeded');assert.equal(sends,1);assert.equal((await processNotification(ctx,id,notifier)).duplicate,true);assert.equal((await db.query('SELECT id FROM report_snapshots WHERE id=$1',[report.id])).rows.length,1);});
 await t.test('mode mismatch blocks live transport in mock records',async()=>{await assert.rejects(()=>archiveReportToDrive(ctx,report.id,{...drive,mode:'live'}),{code:'MODE_MISMATCH'});});
 }finally{await db.close();}
});

test('QA safety: configured capability proof, metric gaps and archive end evidence',async()=>{
 const db=await createTestDatabase();try{const ctx=context(db);await assert.rejects(()=>refreshBaiduReadiness(ctx,randomUUID(),createBaiduAdapter({mode:'mock'})),{code:'INTEGRATION_REQUIRED'});assert.equal((await db.query("SELECT id FROM settings WHERE key LIKE 'ads.readiness:%'")).rows.length,0);const seven=await getSevenDayCompleteness(ctx,{start:'2026-09-25',end:'2026-10-01'});assert.equal(seven.passed,false);assert.equal(seven.realAcceptance,false);assert.equal(seven.completeBusinessDays,0);assert.deepEqual(calculateSeoMetrics({source:'not-connected',observedAt:null,clicks:null,impressions:null,positions:null,evidenceRef:null}),{status:'missing',ctr:null,averagePosition:null});const zero=calculateSeoMetrics({source:'qa',observedAt:new Date().toISOString(),clicks:0,impressions:0,positions:[],evidenceRef:'mock/actual-zero'});assert.equal(zero.ctr,null);assert.equal(zero.averagePosition,null);assert.equal(advertisingRetention({endedAt:null,retainUntil:'2020-01-01T00:00:00Z',legalHold:false},new Date('2030-01-01')).deletable,false);assert.equal(advertisingRetention({endedAt:'2024-02-29T00:00:00Z',retainUntil:null,legalHold:false},new Date('2027-02-27')).deletable,false);assert.equal(advertisingRetention({endedAt:'2024-02-29T00:00:00Z',retainUntil:null,legalHold:false},new Date('2027-03-01')).retainUntil,'2027-02-28T00:00:00.000Z');assert.equal(advertisingRetention({endedAt:'2020-01-01T00:00:00Z',retainUntil:null,legalHold:true},new Date('2030-01-01')).deletable,false);}finally{await db.close();}
});
