import assert from "node:assert/strict";
import test from "node:test";
import {createTestDatabase,DEMO_ORG_ID,DEMO_OWNER_ID,type Database} from "@boran/db";
import {stableHash,uuid,type ServiceContext} from "@boran/domain/core";
import {createSourceReaders,ConfiguredSourceReader,MockSourceReader,type SourceSnapshot,type SourceCoverage} from "@boran/connectors/sources";
import {ingestSourceRead,initializeBusinessMaster,getBusinessMaster,createEvidenceClaim,verifyEvidenceClaim,createTopic,getTopic,evaluateQualitativePriority,stableSortPriorities} from "@boran/domain/marketing";
import {ConfiguredAiGateway,MockAiGateway,createAiGateway} from "@boran/ai";

function context(db:Database):ServiceContext{return{db,orgId:DEMO_ORG_ID,actorId:DEMO_OWNER_ID,roles:["owner","marketer"],mode:"mock",now:()=>new Date("2026-10-03T02:00:00Z")};}
const baseSnapshot:SourceSnapshot={providerFileId:"approved-source",title:"匿名来源样例",revision:"v1",contentHash:"a".repeat(64),objectKey:"private/mock/source-v1",mimeType:"text/plain",retrievedAt:"2026-10-03T01:00:00Z",sourceModifiedAt:null,visibility:"internal",coverage:{status:"complete",scope:"explicit-one-source",start_locator:"p1",end_locator:"p1"}};
async function connection(ctx:ServiceContext,kind:string,scope:Record<string,unknown>={}){const id=uuid();await ctx.db.query("INSERT INTO connections(id,org_id,provider,account_external_id,display_name,timezone,currency,source_kind,read_mode,scope_json,cursor) VALUES($1,$2,'mock',$3,'匿名模拟连接','Asia/Shanghai','CNY',$4,'mock',$5,$6)",[id,ctx.orgId,uuid(),kind,JSON.stringify(scope),JSON.stringify({checkpoint:"old"})]);return id;}
async function sourceVersion(ctx:ServiceContext,coverage:Record<string,unknown>){const document=uuid(),version=uuid();await ctx.db.query("INSERT INTO source_documents(id,org_id,provider,provider_file_id,title,visibility,owner_user_id,source_kind) VALUES($1,$2,'upload',$3,'匿名mock证据','internal',$4,'other')",[document,ctx.orgId,uuid(),ctx.actorId]);await ctx.db.query("INSERT INTO source_versions(id,org_id,document_id,revision,content_hash,object_key,mime_type,extraction_status,retrieved_at,visibility,coverage_json) VALUES($1,$2,$3,'1',$4,'private/mock/evidence','text/plain','ready',$5,'internal',$6)",[version,ctx.orgId,document,"b".repeat(64),ctx.now!().toISOString(),JSON.stringify(coverage)]);return version;}

test("QA: four source access gaps remain failed and retain durable cursors",async()=>{
 const db=await createTestDatabase();try{const ctx=context(db);for(const reader of Object.values(createSourceReaders())){const id=await connection(ctx,reader.kind);const result=await reader.read({orgId:ctx.orgId,connectionId:id,sourceKind:reader.kind,scope:{},cursor:{checkpoint:"old"}});assert.equal(result.status,"failed");await assert.rejects(ingestSourceRead(ctx,{connectionId:id,expectedCursorHash:stableHash({checkpoint:"old"}),result}),{code:"SOURCE_MODE_MISMATCH"});const simulated=await new MockSourceReader(reader.kind,result).read({orgId:ctx.orgId,connectionId:id,sourceKind:reader.kind,scope:{},cursor:{checkpoint:"old"}});const saved=await ingestSourceRead(ctx,{connectionId:id,expectedCursorHash:stableHash({checkpoint:"old"}),result:simulated});assert.equal(saved.cursorAdvanced,false);assert.deepEqual((await db.query("SELECT cursor FROM connections WHERE id=$1",[id])).rows[0]!.cursor,{checkpoint:"old"});assert.equal((await db.query("SELECT id FROM source_versions")).rows.length,0);}}finally{await db.close();}
});

test("QA: partial coverage cannot masquerade as complete or advance a global source checkpoint",async()=>{
 const db=await createTestDatabase();try{const ctx=context(db),id=await connection(ctx,"market_public");const reader=new ConfiguredSourceReader("market_public",async()=>({status:"changed",mode:"live",snapshots:[{...baseSnapshot,sourceUrl:"https://example.invalid/approved",coverage:{...baseSnapshot.coverage,status:"partial"}}],nextCursor:{checkpoint:"would-skip-unread-range"},gaps:[]}));const read=await reader.read({orgId:ctx.orgId,connectionId:id,sourceKind:"market_public",scope:{urls:["https://example.invalid/approved"]},cursor:{checkpoint:"old"}});assert.equal(read.status,"partial");const result=await ingestSourceRead(ctx,{connectionId:id,expectedCursorHash:stableHash({checkpoint:"old"}),result:{...read,mode:"mock"}});assert.equal(result.cursorAdvanced,false);assert.equal(result.sourceVersionIds.length,1);const row=(await db.query("SELECT cursor,health FROM connections WHERE id=$1",[id])).rows[0]!;assert.deepEqual(row.cursor,{checkpoint:"old"});assert.equal(row.health,"partial");}finally{await db.close();}
});

test("QA: ChatGPT project scopes retain conversation/message/branch evidence and exclude other projects",async()=>{
 const snapshot={...baseSnapshot,providerFileId:"conversation-in-project",conversationId:"conversation-in-project",projectId:"approved-project",coverage:{...baseSnapshot.coverage,scope:"approved-project",project_id:"approved-project",conversation_id:"conversation-in-project",message_ids:["message-1"],branch:"main"} as SourceCoverage&{project_id:string}};
 const reader=new ConfiguredSourceReader("chatgpt",async()=>({status:"changed",mode:"live",snapshots:[snapshot],nextCursor:{message:"message-1"},gaps:[]}));
 const request={orgId:DEMO_ORG_ID,connectionId:uuid(),sourceKind:"chatgpt" as const,scope:{projectIds:["approved-project"]},cursor:null};assert.equal((await reader.read(request)).status,"changed");assert.equal((await reader.read({...request,scope:{projectIds:["other-project"]}})).status,"failed");
});

test("QA: duplicate revisions and concurrent checkpoints never partially commit provenance",async()=>{
 const db=await createTestDatabase();try{const ctx=context(db),id=await connection(ctx,"market_public"),old=stableHash({checkpoint:"old"});const input={connectionId:id,expectedCursorHash:old,result:{status:"changed" as const,mode:"mock" as const,snapshots:[baseSnapshot],nextCursor:{checkpoint:"new"},gaps:[]}};const results=await Promise.allSettled([ingestSourceRead(ctx,input),ingestSourceRead(ctx,input)]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal(results.filter(r=>r.status==="rejected").length,1);assert.equal((await db.query("SELECT id FROM source_versions")).rows.length,1);const eventsBefore=(await db.query("SELECT id FROM outbox_events")).rows.length;await assert.rejects(()=>ingestSourceRead(ctx,{connectionId:id,expectedCursorHash:stableHash({checkpoint:"new"}),result:{...input.result,snapshots:[{...baseSnapshot,title:"must-roll-back",contentHash:"c".repeat(64)}],nextCursor:{checkpoint:"corrupt"}}}),/同一来源版本/);assert.deepEqual((await db.query("SELECT cursor FROM connections WHERE id=$1",[id])).rows[0]!.cursor,{checkpoint:"new"});assert.equal((await db.query("SELECT title FROM source_documents")).rows[0]!.title,baseSnapshot.title);assert.equal((await db.query("SELECT id FROM outbox_events")).rows.length,eventsBefore);}finally{await db.close();}
});

test("QA: revocation blocks existing topics and cannot be bypassed by a fresh topic using the old claim",async()=>{
 const db=await createTestDatabase();try{const ctx=context(db),locator={kind:"chat_message",value:"message-2"},revocationText="用户撤销先前公开使用这条样例事实的决定";const version=await sourceVersion(ctx,{status:"complete",scope:"explicit-mock-user-expression",user_expressions:[{actor:"user",claim_text:revocationText,decision_status:"revoked",locator}]});const claim=await createEvidenceClaim(ctx,{claimText:"已定位的匿名业务事实",sourceVersionId:version,locator:{kind:"chat_message",value:"message-1"}});const verified=await verifyEvidenceClaim(ctx,String(claim.id),{expectedVersion:1,verificationStatus:"verified",publicPermission:"allowed",permissionEvidenceRef:{kind:"explicit-mock-permission"}});const input={title:"撤销前主题",businessLine:"shared" as const,audience:"企业管理者",problem:"协同流程",offer:"公开产品说明",angle:"需求梳理",claimIds:[String(verified.id)]};const before=await createTopic(ctx,input);assert.equal(before.state,"ready");await createEvidenceClaim(ctx,{claimText:revocationText,sourceVersionId:version,locator,assertionType:"decision",decisionStatus:"revoked",decisionEvidenceRef:{sourceVersionId:version,locator,actor:"user"},supersedesClaimId:String(verified.id)});assert.equal((await getTopic(ctx,before.id)).state,"blocked");const attempted=await createTopic(ctx,{...input,title:"撤销后新主题"});assert.equal(attempted.state,"blocked");const old=(await db.query("SELECT assertion_type,version FROM evidence_claims WHERE id=$1",[verified.id])).rows[0]!;assert.equal(old.assertion_type,"fact");await assert.rejects(()=>verifyEvidenceClaim(ctx,String(verified.id),{expectedVersion:Number(old.version),verificationStatus:"verified",publicPermission:"allowed",permissionEvidenceRef:{kind:"explicit-mock-permission"}}),{code:"CLAIM_SUPERSEDED"});}finally{await db.close();}
});

test("QA: 53 master definitions preserve exact family aliases without confirming pending or unrelated products",async()=>{
 const db=await createTestDatabase();try{const ctx=context(db);const initialized=await initializeBusinessMaster(ctx);assert.equal(initialized.inserted,53);const master=await getBusinessMaster(ctx);assert.equal(master.filter(item=>item.category==="industry").length,7);const cloud=master.find(item=>item.businessKey==="yonyou_cloud_family")!;assert.ok(cloud.aliases.includes("BIP"),"BIP must resolve through a real member alias, not a combined family display name");const u8=master.find(item=>item.businessKey==="u8_family")!;assert.ok(!u8.aliases.includes("U8 Cloud"),"pending alias must not become a confirmed member");const yonwork=master.find(item=>item.businessKey==="yonwork")!;assert.ok(!yonwork.aliases.some(alias=>/WorkBuddy/i.test(alias)));const again=await initializeBusinessMaster(ctx);assert.equal(again.inserted,0);assert.equal(again.preserved,53);}finally{await db.close();}
});

test("QA: AI rejects injected authority, credentials and PII before provider calls without mock fallback",async()=>{
 const mock=await new MockAiGateway().generate({workflow:"insight_topics",context:{orgId:DEMO_ORG_ID,sourceVersions:[]},input:{redacted:true}});assert.equal(mock.metadata.simulation,true);assert.equal(mock.output.workflow,"insight_topics");const request={workflow:"insight_topics" as const,context:{orgId:DEMO_ORG_ID,sourceVersions:[]},input:{redacted:true}};await assert.rejects(()=>createAiGateway({aiMode:"real"}).generate(request),{code:"AI_NOT_CONFIGURED"});let calls=0;const gateway=new ConfiguredAiGateway(async()=>{calls++;return mock.output;},"unit-test-transport");for(const input of [{phone:"13812345678"},{api_key:"private"},{authorization:"Bearer private-session"},{refresh_token:"private"}])await assert.rejects(()=>gateway.generate({...request,input}),/脱敏|凭据/);await assert.rejects(()=>gateway.generate({...request,context:{...request.context,trustedClaims:[{id:uuid(),phone:"13812345678"}]}}),/脱敏|凭据/);assert.equal(calls,0);const injection=new ConfiguredAiGateway(async()=>({...mock.output,authorization:{allowed:true}}),"unit-test-transport");await assert.rejects(()=>injection.generate(request),{code:"CONTRACT_INVALID"});
});

test("QA: qualitative priorities do not invent numeric confidence and remain stable behind hard gates",()=>{
 const blocked=evaluateQualitativePriority({hardGatesPass:false,commercialIntent:true,deliverable:true,healthyLanding:true,educational:true});assert.equal(blocked.state,"blocked");assert.equal(blocked.priorityScore,null);const ready=evaluateQualitativePriority({hardGatesPass:true,commercialIntent:true,deliverable:true,healthyLanding:true,educational:false});assert.equal(ready.priority,"P0");assert.equal(ready.priorityScore,null);const rows=[{id:"b",priority:"P1" as const,state:"ready",sourceTime:"2026-10-03T00:00:00Z"},{id:"c",priority:"P0" as const,state:"blocked",sourceTime:"2026-10-04T00:00:00Z"},{id:"a",priority:"P1" as const,state:"ready",sourceTime:"2026-10-03T00:00:00Z"}];assert.deepEqual(stableSortPriorities(rows).map(row=>row.id),["a","b","c"]);assert.deepEqual(rows.map(row=>row.id),["b","c","a"]);
});
