import test,{after,before} from 'node:test';
import assert from 'node:assert/strict';
import {createTestDatabase,DEMO_ORG_ID,DEMO_OWNER_ID,DEMO_MARKETER_ID,type Database} from '@boran/db';
import {validateApiRequest} from '@boran/contracts';
import {stableHash,uuid,type ServiceContext} from '../src/core';
import {sanitizePrivateText} from '../src/privacy';
import {ingestPublicEvents,validateAnalyticsConfiguration,pruneExpiredPublicEvents,type PublicEvent} from '../src/events';
let db:Database,ctx:ServiceContext;const time=new Date('2026-10-03T01:00:00Z');const options={rateLimitKey:'synthetic-rate-key'};
before(async()=>{db=await createTestDatabase();ctx={db,orgId:DEMO_ORG_ID,actorId:DEMO_OWNER_ID,roles:['owner','marketer'],mode:'mock',now:()=>time};});after(async()=>{await db?.close();});
async function published(){const item=uuid(),version=uuid(),page=uuid(),approval=uuid(),action=uuid(),release=uuid();
 await db.query("INSERT INTO content_items(id,org_id,kind,business_line,owner_user_id,title) VALUES($1,$2,'landing_page','shared',$3,'匿名统计脱敏验收')",[item,ctx.orgId,ctx.actorId]);await db.query("INSERT INTO content_versions(id,org_id,content_item_id,version_no,body_json,claim_ids,payload_hash,review_status,warnings) VALUES($1,$2,$3,1,'{}','{}',$4,'approved','[]')",[version,ctx.orgId,item,stableHash({})]);await db.query("INSERT INTO pages(id,org_id,host,path,owner_system,business_line,canonical_url,index_policy,owner_user_id) VALUES($1,$2,'example.invalid',$3,'marketing','shared',$4,'noindex',$5)",[page,ctx.orgId,`/test/${page}`,`https://example.invalid/test/${page}`,ctx.actorId]);
 await db.query("INSERT INTO approvals(id,org_id,action_type,target,version_id,payload,payload_hash,before_snapshot,after_preview,budget_impact,requested_by,decision,decided_by,decided_at,expires_at,version) VALUES($1,$2,'content.publish',$3,$4,'{}',$5,'{}','{}','{}',$6,'consumed',$6,now(),now()+interval '1 day',1)",[approval,ctx.orgId,JSON.stringify({page_id:page}),version,stableHash({}),ctx.actorId]);await db.query("INSERT INTO execution_actions(id,org_id,approval_id,idempotency_key,request_hash,state,before_snapshot,version,action_type,target,version_id,payload,payload_hash) VALUES($1::uuid,$2,$3,$1::text,$4,'submitted','{}',1,'content.publish',$5,$6,'{}',$4)",[action,ctx.orgId,approval,stableHash({}),JSON.stringify({page_id:page}),version]);await db.query("INSERT INTO releases(id,org_id,page_id,content_version_id,action_id,published_at,seo_snapshot,route_config_version) VALUES($1,$2,$3,$4,$5,now(),'{}','test-v1')",[release,ctx.orgId,page,version,action]);await db.query('UPDATE pages SET published_release_id=$3 WHERE org_id=$1 AND id=$2',[ctx.orgId,page,release]);return {page,release};
}
function view(source:{page:string;release:string}):PublicEvent{return {event_id:uuid(),event_type:'page_view',occurred_at:time.toISOString(),page_id:source.page,release_id:source.release};}
test('anonymous total works with privacy off, concurrent UUID retries dedupe and persist no visitor identifiers',async()=>{
 const source=await published(),event=view(source);const results=await Promise.all([ingestPublicEvents(ctx,{events:[event]},options),ingestPublicEvents(ctx,{events:[event]},options),ingestPublicEvents(ctx,{events:[event]},options)]);assert.equal(results.reduce((sum,r)=>sum+r.data.accepted_count,0),1);assert.equal(results.reduce((sum,r)=>sum+r.data.duplicate_count,0),2);results.forEach(r=>validateApiRequest('EventAccepted',r));
 const row=(await db.query('SELECT * FROM web_events WHERE org_id=$1 AND event_id=$2',[ctx.orgId,event.event_id])).rows[0]!;assert.equal(row.anonymous_id,null);assert.equal(row.session_id,null);assert.deepEqual(row.attribution,{});assert.equal((row.properties as Record<string,unknown>).collection_mode,'anonymous_page_total');assert.equal((row.properties as Record<string,unknown>).synthetic,true);
 await assert.rejects(ingestPublicEvents(ctx,{events:[{...event,occurred_at:new Date(time.getTime()-1000).toISOString()}]},options),{code:'IDEMPOTENCY_CONFLICT'});
});
test('events reject arbitrary properties, raw query URLs, unknown top fields, nonrandom identities and future timestamps',async()=>{
 assert.equal(sanitizePrivateText('7125ba92-3008-41f0-ad39-1234567a5f57'),'7125ba92-3008-41f0-ad39-1234567a5f57');
 const source=await published(),event=view(source);for(const input of [{...event,properties:{contact_email:'only-synthetic@example.invalid'}},{...event,properties:{headers:{authorization:'synthetic-secret'}}},{...event,attribution:{query:'email=only-synthetic@example.invalid'}},{...event,attribution:{referrer_origin:'https://example.invalid/private/path?x=secret'}}])await assert.rejects(ingestPublicEvents(ctx,{events:[input]} as never,options));
 await assert.rejects(ingestPublicEvents(ctx,{events:[event],org_id:uuid()} as never,options),{code:'CONTRACT_INVALID'});await assert.rejects(ingestPublicEvents(ctx,{events:[{...event,attribution:{session_id:'00000000-0000-1000-8000-000000000001'}}]},options),{code:'INVALID_EVENT_IDENTIFIER'});await assert.rejects(ingestPublicEvents(ctx,{events:[{...event,occurred_at:new Date(time.getTime()+3600000).toISOString()}]},options),{code:'INVALID_EVENT_TIME'});assert.equal((await db.query('SELECT id FROM web_events WHERE event_id=$1',[event.event_id])).rowCount,0);
});
test('only current published page/release can accept events; contradictory batch rolls back atomically',async()=>{
 const source=await published(),event=view(source);await assert.rejects(ingestPublicEvents(ctx,{events:[event]},{...options,publicHost:'foreign.example.invalid'}),{code:'EVENT_PAGE_NOT_PUBLISHED'});await assert.rejects(ingestPublicEvents(ctx,{events:[{...event,release_id:uuid()}]},options),{code:'EVENT_PAGE_NOT_PUBLISHED'});await db.query('UPDATE pages SET published_release_id=NULL WHERE id=$1',[source.page]);await assert.rejects(ingestPublicEvents(ctx,{events:[event]},options),{code:'EVENT_PAGE_NOT_PUBLISHED'});await db.query('UPDATE pages SET published_release_id=$2 WHERE id=$1',[source.page,source.release]);
 await assert.rejects(ingestPublicEvents(ctx,{events:[event,{...event,occurred_at:new Date(time.getTime()-1000).toISOString()}]},options),{code:'IDEMPOTENCY_CONFLICT'});assert.equal((await db.query('SELECT id FROM web_events WHERE event_id=$1',[event.event_id])).rowCount,0);
});
test('behavior and attribution require separate owner config, current privacy gate and explicit per-event consent',async()=>{
 const source=await published(),event={...view(source),event_type:'cta_click' as const,properties:{analytics_consent:true,privacy_notice_version:'mock-v1',cta_id:'consultation'}};await assert.rejects(ingestPublicEvents(ctx,{events:[event]},options),{code:'privacy_configuration_required'});
 const input={enabled:true,notice_version:'mock-v1',purpose:'仅合成事件功能验收',lawful_basis:'consent',retention_days:1,allowed_event_types:['page_view','cta_click','form_start','form_submit'],allow_attribution:true,allow_identifiers:true};await assert.rejects(validateAnalyticsConfiguration(ctx,{...input,password:'must-not-persist'}),{code:'INVALID_ANALYTICS_CONFIGURATION'});await assert.rejects(validateAnalyticsConfiguration({...ctx,actorId:DEMO_MARKETER_ID,roles:['owner']},input),{code:'FORBIDDEN'});const config=await validateAnalyticsConfiguration(ctx,input);await db.query("INSERT INTO settings(org_id,key,value,schema_version,updated_by) VALUES($1,'analytics_configuration',$2,1,$3)",[ctx.orgId,JSON.stringify(config),ctx.actorId]);
 const allowed={...options,internalTest:true};await assert.rejects(ingestPublicEvents(ctx,{events:[{...event,properties:{cta_id:'consultation'}}]},allowed),{code:'ANALYTICS_CONSENT_REQUIRED'});await assert.rejects(ingestPublicEvents(ctx,{events:[{...event,properties:{...event.properties,privacy_notice_version:'outdated'}}]},allowed),{code:'ANALYTICS_CONSENT_REQUIRED'});
 const observation={...event,attribution:{utm_source:'tagged-only@example.invalid',click_id:'untrusted-only@example.invalid',session_id:uuid(),anonymous_id:uuid()}};const result=await ingestPublicEvents(ctx,{events:[observation]},allowed);assert.equal(result.data.accepted_count,1);const row=(await db.query('SELECT * FROM web_events WHERE event_id=$1',[event.event_id])).rows[0]!;assert.ok(/^[a-f0-9]{64}$/.test(String((row.attribution as Record<string,unknown>).click_id)));assert.equal(JSON.stringify(row).includes('@example.invalid'),false);assert.equal(row.session_id,observation.attribution.session_id);assert.equal((row.properties as Record<string,unknown>).collection_mode,'consented_behavior');
 await db.query('UPDATE users SET active=false WHERE id=$1',[ctx.actorId]);try{await assert.rejects(ingestPublicEvents(ctx,{events:[{...observation,event_id:uuid()}]},allowed),{code:'ANALYTICS_CONFIGURATION_REQUIRED'});}finally{await db.query('UPDATE users SET active=true WHERE id=$1',[ctx.actorId]);}
});
test('event rate limits persist across service instances and duplicate successful retries do not consume slots',async()=>{
 const source=await published(),event=view(source),limited={rateLimitKey:'separate-persistent-rate-client'};await ingestPublicEvents(ctx,{events:[event]},limited);for(let i=1;i<60;i++)await ingestPublicEvents({...ctx},{events:[view(source)]},limited);await assert.rejects(ingestPublicEvents(ctx,{events:[view(source)]},limited),{code:'RATE_LIMITED'});const replay=await ingestPublicEvents({...ctx},{events:[event]},limited);assert.equal(replay.data.accepted_count,0);assert.equal(replay.data.duplicate_count,1);
});
test('retention cleanup requires current service authorization and preserves unexpired events and audit dedupe',async()=>{
 const source=await published(),event=view(source);await ingestPublicEvents(ctx,{events:[event]},{rateLimitKey:'retention-client'});await assert.rejects(pruneExpiredPublicEvents({...ctx,actorId:DEMO_MARKETER_ID,roles:['owner']}),{code:'FORBIDDEN'});assert.equal((await pruneExpiredPublicEvents(ctx)).deleted_count,0);
 const future={...ctx,now:()=>new Date(time.getTime()+2*86400000)};assert.ok((await pruneExpiredPublicEvents(future)).deleted_count>0);assert.equal((await db.query('SELECT id FROM web_events WHERE event_id=$1',[event.event_id])).rowCount,0);assert.equal((await db.query("SELECT key FROM idempotency_records WHERE scope='public_web_event' AND key=$1",[event.event_id])).rowCount,1);const replay=await ingestPublicEvents(future,{events:[event]},{rateLimitKey:'retention-client'});assert.equal(replay.data.duplicate_count,1);assert.equal(replay.data.accepted_count,0);assert.equal((await db.query('SELECT id FROM web_events WHERE event_id=$1',[event.event_id])).rowCount,0);
});
