import test from 'node:test';
import assert from 'node:assert/strict';
import {createTestDatabase,openDatabase,migrateDatabase,seedDemo,DEMO_ORG_ID,DEMO_OWNER_ID,type Database} from '@boran/db';
import {createPolicy,activatePolicy,reconcileServiceExecutionAction} from '../src/execution';
import {createContentItem,createContentVersion} from '../src/content';
import {uuid,stableHash,type ServiceContext} from '../src/core';
async function database():Promise<Database>{
 if(!process.env.BORAN_TEST_PG_URL)return createTestDatabase();
 const admin=await openDatabase({url:process.env.BORAN_TEST_PG_URL,mode:'live'}),schema=`reconciliation_test_${uuid().replace(/-/g,'')}`;await admin.query(`CREATE SCHEMA ${schema}`);const url=new URL(process.env.BORAN_TEST_PG_URL);url.searchParams.set('options',`-csearch_path=${schema}`);
 const db=await openDatabase({url:url.toString(),mode:'live'});await migrateDatabase(db);await seedDemo(db);const close=db.close;db.close=async()=>{try{await close();await admin.query(`DROP SCHEMA ${schema} CASCADE`);}finally{await admin.close();}};return db;
}
test('service reconciliation reads stored synthetic receipts, preserves stops, and refuses mismatched identity or results',async t=>{
 const db=await database(),owner:ServiceContext={db,orgId:DEMO_ORG_ID,actorId:DEMO_OWNER_ID,roles:['owner'],mode:'live',now:()=>new Date('2026-10-04T02:00:00Z')},service={...owner,actorId:'synthetic-authenticated-worker',actorType:'service' as const,roles:['service']};
 try{
  const connectionId=uuid(),accountId=uuid();await db.query("INSERT INTO connections(id,org_id,provider,account_external_id,display_name,timezone,currency,read_mode) VALUES($1,$2,'fixture',$3,'Synthetic receipt test','Asia/Shanghai','CNY','native_api')",[connectionId,owner.orgId,'synthetic-account']);await db.query("INSERT INTO platform_accounts(id,org_id,connection_id,provider,account_external_id,display_name) VALUES($1,$2,$3,'fixture','synthetic-account','Synthetic account')",[accountId,owner.orgId,connectionId]);
  const policy=await createPolicy(owner,{name:'Synthetic policy',businessScope:{business_lines:['shared']},accountIds:[accountId],allowedActions:['external.publish','ads.update'],dailyBudgetMinor:100,totalBudgetMinor:100,stopConditions:{owner_stop:true}});const policyId=String((await db.query('SELECT id FROM policy_versions WHERE policy_id=$1',[policy.id])).rows[0]!.id);await activatePolicy(owner,String(policy.id),policyId,1);
  const item=await createContentItem(owner,{title:'Synthetic validated content',business_line:'shared',kind:'article'}),version=await createContentVersion(owner,item.id,{title:'Synthetic validated content',claim_ids:[],modules:[{type:'hero',schema_version:1,data:{headline:'服务介绍',description:'说明',cta:{label:'了解',href:'/services',action:'navigate'}}}]},0);
  async function fixture(type:'publish'|'ad_write',outcome:'verified'|'rejected'='verified'){
   const actionId=uuid(),originalId=uuid(),commandId=uuid(),payload=type==='publish'?{title:'Synthetic validated content'}:{price:2.5},hash=stableHash(payload),evidence={verified:true,kind:'api_readback',externalAccountId:'synthetic-account',capturedAt:'2026-10-04T02:00:00Z',evidenceRef:'synthetic-test-receipt-only',...(outcome==='verified'?{labelsVerified:true,contentHash:hash}:{})},data=type==='publish'?{external_id:'synthetic-resource',published_url:'https://publish.example.invalid/posts/synthetic',review_status:outcome==='rejected'?'rejected':'published'}:{external_id:'synthetic-keyword',effective_fields:{price:2.5,accountId:'synthetic-account'}};
   await db.query("INSERT INTO execution_actions(id,org_id,idempotency_key,request_hash,state,before_snapshot,policy_version_id,action_type,target,version_id,payload,payload_hash) VALUES($1,$2,$3,$4,'unknown','{}',$5,$6,$7,$8,$9,$10)",[actionId,owner.orgId,uuid(),stableHash({actionId}),policyId,type==='publish'?'external.publish':'ads.update',JSON.stringify({platform_account_id:accountId}),type==='publish'?version.id:null,JSON.stringify(payload),hash]);
   const state=outcome==='verified'?'succeeded':'failed',result={status:outcome,evidence,data};
   await db.query('INSERT INTO browser_commands(id,org_id,platform_account_id,execution_action_id,command_type,idempotency_key,state,input_ref,result_ref,finished_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[originalId,owner.orgId,accountId,actionId,type,uuid(),state,JSON.stringify({mode:'live',refs:type==='publish'?{content_version_id:version.id}:{action_snapshot_id:actionId}}),JSON.stringify({...result,reconciliationCommandId:commandId}),'2026-10-04T02:00:00Z']);
   await db.query("INSERT INTO browser_commands(id,org_id,platform_account_id,execution_action_id,command_type,idempotency_key,state,input_ref,result_ref,finished_at) VALUES($1,$2,$3,$4,'reconcile',$5,$6,$7,$8,$9)",[commandId,owner.orgId,accountId,actionId,uuid(),state,JSON.stringify({mode:'live',refs:{reconcile_command_id:originalId}}),JSON.stringify(result),'2026-10-04T02:00:00Z']);return {actionId,commandId,data};
  }
  await t.test('stored publication proof settles after write stop and duplicate readback does not add attempts',async()=>{
   const f=await fixture('publish');await db.query('UPDATE organizations SET write_enabled=false WHERE id=$1',[owner.orgId]);const first=await reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found'});assert.equal(first.state,'succeeded');assert.equal(first.external_id,'synthetic-resource');const repeat=await reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found'});assert.equal(repeat.version,first.version);assert.equal(Number((await db.query('SELECT count(*) AS n FROM action_attempts WHERE action_id=$1',[f.actionId])).rows[0]!.n),1);
  });
  await t.test('a rejected review stays failed and cannot become published success',async()=>{const f=await fixture('publish','rejected');await assert.rejects(reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found'}),{code:'VERIFICATION_REQUIRED'});const result=await reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'rejected'});assert.equal(result.state,'failed');assert.equal(result.verified_at,null);});
  await t.test('caller proof, mock mode, user identity and wrong account evidence cannot settle real results',async()=>{
   const f=await fixture('publish');await assert.rejects(reconcileServiceExecutionAction(owner,f.actionId,{commandId:f.commandId,outcome:'found'}),{code:'SERVICE_IDENTITY_REQUIRED'});await assert.rejects(reconcileServiceExecutionAction({...service,mode:'mock'},f.actionId,{commandId:f.commandId,outcome:'found'}),{code:'MOCK_NOT_LIVE_SUCCESS'});await assert.rejects(reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found',externalId:'invented'}),{code:'RECONCILIATION_BINDING_REQUIRED'});await assert.rejects(reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found',afterSnapshot:{published_url:'https://invented.invalid/'}}),{code:'RECONCILIATION_BINDING_REQUIRED'});
   await db.query("UPDATE browser_commands SET result_ref=jsonb_set(result_ref,'{evidence,externalAccountId}',to_jsonb('wrong-account'::text)) WHERE id=$1",[f.commandId]);await assert.rejects(reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found'}),{code:'VERIFICATION_REQUIRED'});
  });
  await t.test('Baidu readback must match all requested effective fields and actual account',async()=>{const f=await fixture('ad_write');await db.query("UPDATE browser_commands SET result_ref=jsonb_set(result_ref,'{data,effective_fields,price}','99'::jsonb) WHERE id=$1",[f.commandId]);await assert.rejects(reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found'}),{code:'VERIFICATION_REQUIRED'});await db.query("UPDATE browser_commands SET result_ref=jsonb_set(result_ref,'{data,effective_fields,price}','2.5'::jsonb) WHERE id=$1",[f.commandId]);const result=await reconcileServiceExecutionAction(service,f.actionId,{commandId:f.commandId,outcome:'found'});assert.equal(result.state,'succeeded');});
 }finally{await db.close();}
});
