import Link from "next/link";
import { Badge, SectionTitle } from "@boran/ui";
import { Icon } from "@/components/icon";
import { overviewFixture } from "@/lib/fixtures";

const exceptions = [
  { id: "01", name: "平台连接未配置", detail: "资料来源、内容发布与线索回收仍缺少业务连接，自动化工作流尚不能运行。", next: "查看连接设置", icon: "link" as const, badge: "连接缺口" },
  { id: "02", name: "投放预算未批准", detail: "当前没有有效的预算与操作范围批准记录。广告投放与预算调整保持关闭。", next: "查看执行边界", icon: "chart" as const, badge: "等待批准" },
  { id: "03", name: "企业身份尚未接入", detail: "当前是本地模拟身份。真实人员、角色和企业访问控制将在业务接入阶段配置。", next: "查看身份状态", icon: "lock" as const, badge: "身份待接入" },
];

export default function OverviewPage() {
  return <>
    <div className="page-heading"><div><p className="eyebrow">DAILY WORKSPACE</p><h1>今日工作<span className="heading-dot">.</span></h1><p>先处理阻塞，再推进推广。</p></div><Link href="/themes" className="button button-secondary">查看推广主题<Icon name="arrow" size={17} /></Link></div>
    <section className="system-summary" aria-labelledby="system-summary-title"><div className="summary-main"><span className="summary-icon"><Icon name="lock" size={24} /></span><div><div className="summary-label"><span className="status-dot" /><span>等待接通</span></div><h2 id="system-summary-title">系统正在准备，真实执行已关闭</h2><p>连接未配置，预算未批准。目前可以浏览主题和测试报告，无法发布、投放或写入业务数据。</p></div></div><div className="summary-foot"><span><Icon name="eye" size={17} />当前展示隔离的模拟数据</span><Link href="/settings">查看接入清单<Icon name="arrow" size={16} /></Link></div></section>
    <div className="overview-stats" aria-label="演练摘要"><div className="stat-card"><div className="stat-label">例外待办<Icon name="alert" size={18} /></div><div className="stat-value">{overviewFixture.demoExceptions}<span>项</span></div><p>均为接入前的必要准备</p></div><div className="stat-card"><div className="stat-label">演练主题<Icon name="layers" size={18} /></div><div className="stat-value">{overviewFixture.demoThemes}<span>个</span></div><p>用于确认主题管理界面</p></div><div className="stat-card"><div className="stat-label">演练任务<Icon name="file" size={18} /></div><div className="stat-value">{overviewFixture.demoTasks}<span>项</span></div><p>未产生任何真实发布</p></div><div className="stat-card stat-card-muted"><div className="stat-label">真实业务结果<Icon name="chart" size={18} /></div><div className="stat-value empty-value">—</div><p>尚无可用的真实数据</p></div></div>
    <div className="overview-columns"><section className="panel exception-panel"><SectionTitle title="需要你处理" description="接入前的例外与连接缺口" action={<Badge tone="amber">3 项阻塞</Badge>} /><div className="exception-list">{exceptions.map((item) => <details className="exception-item" key={item.id}><summary><span className="exception-icon"><Icon name={item.icon} size={20} /></span><span className="exception-text"><strong>{item.name}</strong><span>{item.badge}</span></span><Icon name="chevron" size={18} className="details-chevron" /></summary><div className="exception-detail"><p>{item.detail}</p><Link href="/settings">{item.next}<Icon name="arrow" size={15} /></Link></div></details>)}</div><div className="panel-note"><Icon name="lock" size={16} /><span>接通并批准范围后，规则内任务才能自动执行。</span></div></section>
    <section className="panel workflow-panel"><SectionTitle title="推广工作流" description="从资料到效果，形成可核验的闭环" /><ol className="workflow-list">{[{ title: "资料与洞察", detail: "发现可推广的业务问题", status: "待连接" }, { title: "主题与内容", detail: "明确受众，准备素材与页面", status: "可预览" }, { title: "发布与投放", detail: "在批准范围内执行并回读核验", status: "已关闭" }, { title: "线索与复盘", detail: "回收真实线索，复盘推广结果", status: "待连接" }].map((step, index) => <li key={step.title}><span className={`step-number ${index === 1 ? "current" : ""}`}>{String(index + 1).padStart(2, "0")}</span><div><strong>{step.title}</strong><p>{step.detail}</p></div><span className={`step-status ${index === 1 ? "current" : ""}`}>{step.status}</span></li>)}</ol></section></div>
    <section className="panel demo-tasks"><SectionTitle title="主题推进预览" description="以下为演练任务，不代表已经采集、生成或发布" action={<Link className="text-link" href="/themes">全部主题<Icon name="arrow" size={16} /></Link>} /><div className="task-table-wrapper"><table className="task-table"><thead><tr><th>推广主题 / 演练任务</th><th>当前阶段</th><th>下一步</th><th>状态</th></tr></thead><tbody><tr><td><strong>企业流程协同</strong><span>补充受众问题与素材范围</span></td><td>主题准备</td><td>确认方向</td><td><Badge tone="amber">待完善</Badge></td></tr><tr><td><strong>经营数据管理</strong><span>检查内容边界与可验证事实</span></td><td>内容审核</td><td>检查预览</td><td><Badge tone="blue">待审核</Badge></td></tr><tr><td><strong>数字化服务入门</strong><span>梳理服务范围与项目准备事项</span></td><td>主题草稿</td><td>补充内容</td><td><Badge>草稿</Badge></td></tr></tbody></table></div></section>
  </>;
}
