import test from 'node:test';
import assert from 'node:assert/strict';
import {createTestDatabase,DEMO_ORG_ID,DEMO_OWNER_ID} from '@boran/db';
import type {ServiceContext} from '@boran/domain/core';
import {handleBrowser} from '../src/lib/handlers/browser';
const request=(method:string,path:string,key:string,version?:string)=>new Request(`http://localhost:3000/api/v1/${path}`,{method,headers:{'content-type':'application/json','idempotency-key':key,...(version?{'if-match':version}:{})}});
test('connection configuration uses an org-bound version and cannot self-report platform readiness',async t=>{
 const db=await createTestDatabase();const ctx:ServiceContext={db,orgId:DEMO_ORG_ID,actorId:DEMO_OWNER_ID,roles:['owner'],mode:'mock'};try{
 const created=await handleBrowser(ctx,request('POST','connections','qa-create-connection'),['connections'],{provider:'mock',account_external_id:'anonymous-test',display_name:'Anonymous account',read_mode:'mock'});assert.equal(created!.status,201);const row=(await created!.json()).data as {id:string;edit_version:string;access_status:string;enabled_for_reporting:boolean};assert.equal(row.access_status,'not_configured');assert.equal(row.enabled_for_reporting,false);assert.equal(/^[a-f0-9]{64}$/.test(row.edit_version),true);
 await t.test('unknown authority fields fail before mutation',async()=>{await assert.rejects(()=>handleBrowser(ctx,request('PATCH',`connections/${row.id}`,'qa-unsafe',row.edit_version),['connections',row.id],{enabled_for_reporting:true,access_status:'connected',capabilities_verified_at:new Date().toISOString()}),{code:'INVALID_REQUEST'});});
 let enabledVersion='';await t.test('report selection is enabled while live connection remains unconfigured',async()=>{const enabled=await handleBrowser(ctx,request('PATCH',`connections/${row.id}`,'qa-enable',row.edit_version),['connections',row.id],{enabled_for_reporting:true,display_name:'Read-only reporting account'});assert.equal(enabled!.status,200);const saved=(await enabled!.json()).data;assert.equal(saved.enabled_for_reporting,true);assert.equal(saved.authoritative_report_type,'campaign_daily');assert.equal(saved.access_status,'not_configured');assert.equal(saved.capabilities_verified_at,null);enabledVersion=saved.edit_version;assert.notEqual(enabledVersion,row.edit_version);const repeated=await handleBrowser(ctx,request('PATCH',`connections/${row.id}`,'qa-enable',row.edit_version),['connections',row.id],{enabled_for_reporting:true,display_name:'Read-only reporting account'});assert.equal((await repeated!.json()).meta.idempotency_replay,true);});
 await t.test('stale version cannot overwrite a more recent configuration',async()=>{await assert.rejects(()=>handleBrowser(ctx,request('PATCH',`connections/${row.id}`,'qa-stale',row.edit_version),['connections',row.id],{display_name:'Overwrite'}),{code:'VERSION_CONFLICT'});});
 await t.test('previous ingestion locks currency and timezone, preserving earlier metric interpretation',async()=>{await db.query("INSERT INTO ingestion_batches(id,org_id,connection_id,report_type,window_start,window_end,file_hash,object_key,schema_version,mapping,state,quality,row_count,error_count) VALUES(gen_random_uuid(),$1,$2,'campaign_daily','2026-09-30','2026-10-01',$3,'private/mock/qa','1','{}','validated','partial',1,0)",[ctx.orgId,row.id,'a'.repeat(64)]);await assert.rejects(()=>handleBrowser(ctx,request('PATCH',`connections/${row.id}`,'qa-currency',enabledVersion),['connections',row.id],{currency:'USD'}),{code:'HISTORICAL_METRIC_SCOPE_LOCKED'});});
 await t.test('foreign organization cannot view or mutate a connection',async()=>{await assert.rejects(()=>handleBrowser({...ctx,orgId:'10000000-0000-4000-8000-000000000001'},request('GET',`connections/${row.id}`,'qa-foreign'),['connections',row.id]),{code:'FORBIDDEN'});});
 }finally{await db.close();}
});
