import {validateApiRequest,SOURCE_KINDS,type SourceKind} from '@boran/contracts';
import {DomainError,stableHash,type ServiceContext} from '@boran/domain/core';
import {activeRoles,requireActiveRole} from '@boran/domain/authz';
import {getBusinessMaster,initializeBusinessMaster,getDistributionManifest,listTopics,getTopic,createTopic,updateTopic,activateTopic,autoScheduleTopics,listInsights,createSource,listSources,getSource,listSourceVersions,updateSource,listClaims,createEvidenceClaim,verifyEvidenceClaim,type TopicInput,type TopicView,type SourceInput} from '@boran/domain/marketing';
import {scheduleRun} from '@boran/worker/queue';
import {jsonData,databaseCommand,expectedVersion,idempotencyKey} from '../http';
type Row=Record<string,unknown>;
const pick=(row:Row,fields:string[])=>Object.fromEntries(fields.map(field=>[field,row[field]??null]));
const topicWire=(topic:TopicView)=>({id:topic.id,insight_id:topic.insightId,title:topic.title,audience:topic.audience,problem:topic.problem,offer:topic.offer,angle:topic.angle,priority:topic.priority,state:topic.state,scheduled_at:topic.scheduledAt,policy_version_id:topic.policyVersionId,claim_ids:topic.claimIds,version:topic.version,industry_key:topic.industryKey,product_family_key:topic.productFamilyKey,domain_keys:topic.domainKeys});
function topicInput(input:Row):Partial<TopicInput> {
  const out:Partial<TopicInput>={};for(const [snake,camel] of [['title','title'],['business_line','businessLine'],['audience','audience'],['problem','problem'],['offer','offer'],['angle','angle'],['claim_ids','claimIds'],['priority','priority'],['industry_key','industryKey'],['product_family_key','productFamilyKey'],['domain_keys','domainKeys'],['insight_id','insightId']])if(input[snake!]!==undefined)(out as Row)[camel!]=input[snake!];return out;
}
async function ensureIds(ctx:ServiceContext,table:'source_versions'|'policy_versions'|'business_goals',ids:string[]):Promise<void> {if(new Set(ids).size!==ids.length)throw new DomainError('INVALID_REFERENCE',422,'引用不可重复');const rows=(await ctx.db.query(`SELECT id FROM ${table} WHERE org_id=$1 AND id=ANY($2::uuid[])`,[ctx.orgId,ids])).rows;if(rows.length!==ids.length)throw new DomainError('INVALID_REFERENCE',422,'引用必须来自同组织');}
export async function handleMarketing(ctx:ServiceContext,request:Request,segments:string[],body:Row={}):Promise<Response|null> {
  const [root,id,command]=segments;const method=request.method;const exact=segments.length;
  if(root==='business-master'&&method==='GET'&&exact===1){const category=new URL(request.url).searchParams.get('category')??'all';if(!['all','product_family','business_domain','industry','service','business_rule'].includes(category))throw new DomainError('INVALID_CATEGORY',422,'主数据分类无效');const masters=await getBusinessMaster(ctx);return jsonData({version:'1.2',category,items:masters.filter(item=>category==='all'||item.category===category).map(item=>({id:item.id,category:item.category,business_key:item.businessKey,version_no:item.versionNo,name:item.name,aliases:item.aliases,status:item.status,payload:item.payload,source_version_id:item.sourceVersionId,source_locator:item.sourceLocator}))});}
  if(root==='business-master'&&id==='initialize'&&method==='POST'&&exact===2){validateApiRequest('EmptyCommand',body);return databaseCommand(ctx,request,body,200,c=>initializeBusinessMaster(c));}
  if(root==='distribution-manifest'&&method==='GET'&&exact===1)return jsonData(await getDistributionManifest(ctx));
  if(root==='topics'&&method==='GET'&&exact===1){const query=new URL(request.url).searchParams;const limit=Number(query.get('limit')??100);if(query.has('cursor'))throw new DomainError('UNSUPPORTED_CURSOR',422,'此版本暂不支持游标分页');return jsonData((await listTopics(ctx,{limit,...(query.has('state')?{state:query.get('state')!}:{})})).map(topicWire));}
  if(root==='topics'&&id&&method==='GET'&&exact===2)return jsonData(topicWire(await getTopic(ctx,id)));
  if(root==='topics'&&method==='POST'&&exact===1){const input=validateApiRequest('TopicCreate',body);return databaseCommand(ctx,request,body,201,async c=>topicWire(await createTopic(c,topicInput(input as Row) as TopicInput)));}
  if(root==='topics'&&id&&method==='PATCH'&&exact===2){const input=validateApiRequest('TopicUpdate',body);return databaseCommand(ctx,request,body,200,async c=>topicWire(await updateTopic(c,id,{...topicInput(input as Row),expectedVersion:expectedVersion(request)})));}
  if(root==='topics'&&id&&command==='activate'&&method==='POST'&&exact===3){const input=validateApiRequest('TopicActivate',body);const version=expectedVersion(request);return databaseCommand(ctx,request,body,200,async c=>{if(input.scheduled_at&&input.platform_account_ids)return topicWire(await activateTopic(c,id,{expectedVersion:version,planCycleId:input.plan_cycle_id,policyVersionId:input.policy_version_id,scheduledAt:input.scheduled_at,platformAccountIds:input.platform_account_ids}));const topic=await getTopic(c,id);if(topic.version!==version)throw new DomainError('VERSION_CONFLICT',409,'主题版本已变化');const result=await autoScheduleTopics(c,{topicIds:[id],planCycleId:input.plan_cycle_id,policyVersionId:input.policy_version_id,...(input.platform_account_ids?{platformAccountIds:input.platform_account_ids}:{}),...(input.scheduled_at?{slotCandidates:[input.scheduled_at]}:{})});if(!result.scheduled[0])throw new DomainError(result.blocked[0]?.code??'TOPIC_BLOCKED',409,'主题尚未满足自动排期条件');return topicWire(result.scheduled[0]);});}
  if(root==='insights'&&method==='GET'&&exact===1)return jsonData((await listInsights(ctx)).map(row=>pick(row,['id','summary','business_line','customer_problem','opportunity','inference_text','priority_score','priority_reason','score_breakdown','data_cutoff','state','claim_ids','priority_label','scoring_mode','metric_policy_version_id','ai_run_id'])));
  if(root==='sources'&&method==='GET'&&exact===1)return jsonData(await listSources(ctx));
  if(root==='sources'&&id&&method==='GET'&&exact===2)return jsonData(await getSource(ctx,id));
  if(root==='sources'&&id&&command==='versions'&&method==='GET'&&exact===3)return jsonData(await listSourceVersions(ctx,id));
  if(root==='sources'&&method==='POST'&&exact===1){const input=validateApiRequest('SourceCreate',body);if(input.object_key)throw new DomainError('UPLOAD_NOT_VERIFIED',409,'来源文件须由服务器验证私有上传，客户端不能直接绑定object_key');const values:SourceInput={provider:input.provider,title:input.title,visibility:input.visibility,...(input.provider_file_id?{providerFileId:input.provider_file_id}:{}),...(input.source_url?{sourceUrl:input.source_url}:{}),...(input.connection_id?{connectionId:input.connection_id}:{}),...(input.source_kind?{sourceKind:input.source_kind}:{}),...(input.conversation_id?{conversationId:input.conversation_id}:{})};return databaseCommand(ctx,request,body,201,c=>createSource(c,values));}
  if(root==='sources'&&id&&['PATCH','DELETE'].includes(method)&&exact===2){const input=validateApiRequest(method==='PATCH'?'SourceUpdate':'SourceDelete',body) as Row;return databaseCommand(ctx,request,body,200,c=>updateSource(c,id,{expectedCurrentVersionId:input['expected_current_version_id'] as string|null,...(typeof input['title']==='string'?{title:input['title']}:{}),...(input['visibility']?{visibility:input['visibility'] as 'internal'|'public'}:{}),...(method==='DELETE'?{deleted:true}:{})}));}
  if(root==='claims'&&method==='GET'&&exact===1)return jsonData(await listClaims(ctx));
  if(root==='claims'&&method==='POST'&&exact===1){const input=validateApiRequest('ClaimCreate',body);if(input.public_permission!=='unknown')throw new DomainError('PUBLIC_PERMISSION_REVIEW_REQUIRED',422,'新主张先登记为公开许可未知，再由核实接口附依据');if(input.decision_status==='confirmed'||input.decision_status==='revoked'||input.decision_evidence_ref)throw new DomainError('USER_EXPRESSION_REQUIRED',422,'客户端不能声明确认依据，须由来源中的用户表达核验');return databaseCommand(ctx,request,body,201,async c=>{const claim=await createEvidenceClaim(c,{claimText:input.claim_text,sourceVersionId:input.source_version_id,locator:input.locator,...(input.assertion_type?{assertionType:input.assertion_type}:{}),...(input.decision_status?{decisionStatus:input.decision_status}:{}),...(input.supersedes_claim_id?{supersedesClaimId:input.supersedes_claim_id}:{}),...(input.valid_until?{validUntil:input.valid_until}:{}),...(input.inference_rationale?{inferenceRationale:input.inference_rationale}:{})});return {claim_id:claim['id'],version:claim['version']};});}
  if(root==='claims'&&id&&command==='verify'&&method==='POST'&&exact===3){const input=validateApiRequest('ClaimVerify',body);return databaseCommand(ctx,request,body,200,c=>verifyEvidenceClaim(c,id,{expectedVersion:expectedVersion(request),verificationStatus:input.verification_status,publicPermission:input.public_permission??'unknown',...(input.visibility?{visibility:input.visibility}:{}),...(input.permission_evidence_ref?{permissionEvidenceRef:input.permission_evidence_ref}:{})}));}
  if(root==='connections'&&id&&command==='sync'&&method==='POST'&&exact===3){
    const input=validateApiRequest('SourceSync',body);
    return databaseCommand(ctx,request,body,202,async c=>{
      await requireActiveRole(c,c.db,'owner','admin','marketer');
      const connection=(await c.db.query('SELECT source_kind,read_mode,access_status FROM connections WHERE org_id=$1 AND id=$2 FOR UPDATE',[c.orgId,id])).rows[0];
      if(!connection)throw new DomainError('NOT_FOUND',404,'来源连接不存在');
      if(c.mode!=='live'&&connection['read_mode']!=='mock')throw new DomainError('LIVE_IDENTITY_REQUIRED',403,'真实来源采集须由独立登录的真实工作空间安排');
      if(!SOURCE_KINDS.includes(connection['source_kind'] as SourceKind))throw new DomainError('INVALID_SOURCE_KIND',422,'此连接不属于四类资料来源');
      if(connection['access_status']==='disabled')throw new DomainError('SOURCE_DISABLED',409,'来源已停用');
      const mode=connection['read_mode']==='mock'?'mock':'live';
      const runInput={connection_id:id,requested_by:c.actorId,actor_id:c.actorId,mode,sync_mode:input.mode};
      const run=await scheduleRun(c.db,{orgId:c.orgId,kind:'source_watch',periodKey:`manual:${stableHash({connectionId:id,actorId:c.actorId,key:idempotencyKey(request)}).slice(0,53)}`,input:runInput,steps:[{key:'source_sync',mode:mode==='mock'?'mock':'read_only',input:runInput}]});
      return {run_id:run['id'],status:run['status'],source_kind:connection['source_kind'],simulation:mode==='mock'};
    });
  }
  if(method==='POST'&&command===undefined&&id==='generate'&&exact===2&&(root==='plans'||root==='insights')){const kind=root==='plans'?'weekly_plan':'insight_topics';const input=validateApiRequest(root==='plans'?'PlanGenerate':'InsightGenerate',body) as Row;await activeRoles(ctx);return databaseCommand(ctx,request,body,202,async c=>{await requireActiveRole(c,c.db,'owner','marketer');if(kind==='weekly_plan')await ensureIds(c,'business_goals',input['goal_ids'] as string[]);else{await ensureIds(c,'source_versions',input['source_version_ids'] as string[]);await ensureIds(c,'policy_versions',[String(input['policy_version_id'])]);const policy=(await c.db.query('SELECT p.status,p.active_version_id,v.id FROM policy_versions v JOIN execution_policies p ON p.org_id=v.org_id AND p.id=v.policy_id WHERE v.org_id=$1 AND v.id=$2',[c.orgId,input['policy_version_id']])).rows[0];if(policy?.['status']!=='active'||policy['active_version_id']!==policy['id'])throw new DomainError('POLICY_INACTIVE',409,'洞察引用的当前执行规则尚未激活');}const run=await scheduleRun(c.db,{orgId:c.orgId,kind,periodKey:`${String(input['week_start']??input['data_cutoff'])}:${stableHash(input).slice(0,20)}`,input:{...input,requested_by:c.actorId},steps:[{key:kind==='weekly_plan'?'draft_plan':'derive_insights',mode:c.mode==='mock'?'mock':'read_only',input}]});return {run_id:run['id'],status:run['status'],simulation:c.mode==='mock'};});}
  return null;
}
